import { afterAll, describe, expect, it } from "vitest";
import { liberarGramaticas, obterParser } from "./gramaticas";
import { coletarComentarios, complexidadeDe, contarLinhas, ehArquivoDeTeste, ehArquivoGerado } from "./metricas";
import type { Linguagem } from "./tipos";

afterAll(() => liberarGramaticas());

async function raiz(l: Linguagem, texto: string) {
  const p = await obterParser(l);
  const arvore = p!.parse(texto)!;
  return { arvore, no: arvore.rootNode };
}

describe("LOC (T-17.06)", () => {
  it("TypeScript: código, comentário (linha e bloco), branco e comentário no fim da linha", async () => {
    const t = "// c1\nconst a = 1; // fim\n/* b\n   c */\n\nfunction f() { return 1 }\n";
    const { arvore, no } = await raiz("typescript", t);
    const loc = contarLinhas(t, coletarComentarios(no, "typescript"));
    expect(loc).toEqual({ loc: 6, loc_codigo: 2, loc_comentario: 3, loc_branco: 1 });
    arvore.delete();
  });

  it("Python: comentários #", async () => {
    const t = "# a\nx = 1  # b\n\ndef f():\n    # c\n    return x\n";
    const { arvore, no } = await raiz("python", t);
    expect(contarLinhas(t, coletarComentarios(no, "python"))).toEqual({ loc: 6, loc_codigo: 3, loc_comentario: 2, loc_branco: 1 });
    arvore.delete();
  });

  it("Java: line_comment e block_comment", async () => {
    const t = "/** doc */\nclass A {\n  // x\n  int f() { return 1; }\n}\n";
    const { arvore, no } = await raiz("java", t);
    expect(contarLinhas(t, coletarComentarios(no, "java"))).toEqual({ loc: 5, loc_codigo: 3, loc_comentario: 2, loc_branco: 0 });
    arvore.delete();
  });

  it("vazio, só quebra de linha, sem \\n final e CRLF", () => {
    expect(contarLinhas("", [])).toEqual({ loc: 0, loc_codigo: 0, loc_comentario: 0, loc_branco: 0 });
    expect(contarLinhas("\n\n", [])).toEqual({ loc: 2, loc_codigo: 0, loc_comentario: 0, loc_branco: 2 });
    expect(contarLinhas("a\nb", [])).toEqual({ loc: 2, loc_codigo: 2, loc_comentario: 0, loc_branco: 0 });
    expect(contarLinhas("a\r\n\r\nb\r\n", [])).toEqual({ loc: 3, loc_codigo: 2, loc_comentario: 0, loc_branco: 1 });
  });
});

describe("complexidade ciclomática (McCabe)", () => {
  it("TypeScript: 1 + if, for, while, case, catch, ternário, && || ??", async () => {
    const t = "function f(a, b) {\n if (a && b) {}\n for (;;) {}\n while (a) {}\n switch (a) { case 1: break; case 2: break; default: break }\n try {} catch (e) {}\n return a ? b : a ?? b;\n}";
    const { arvore, no } = await raiz("typescript", t);
    // 1 + if + && + for + while + 2 case + catch + ternário + ??  = 10
    expect(complexidadeDe(no, "typescript")).toBe(10);
    arvore.delete();
  });

  it("função sem decisão vale 1; operadores aritméticos não contam", async () => {
    const { arvore, no } = await raiz("typescript", "function f(a) { return a + 1 * 2 - 3; }");
    expect(complexidadeDe(no, "typescript")).toBe(1);
    arvore.delete();
  });

  it("Python: if/elif/for/while/except/and/or/ternário", async () => {
    const t = "def f(a, b):\n    if a and b:\n        pass\n    elif a or b:\n        pass\n    for i in a:\n        pass\n    while a:\n        pass\n    try:\n        pass\n    except Exception:\n        pass\n    return 1 if a else 2\n";
    const { arvore, no } = await raiz("python", t);
    // 1 + if + and + elif + or + for + while + except + ternário = 9
    expect(complexidadeDe(no, "python")).toBe(9);
    arvore.delete();
  });

  it("Java: if/for/while/catch/ternário/&&", async () => {
    const t = "class A { int f(int a) { if (a > 0 && a < 9) { for (int i = 0; i < a; i++) {} } try { } catch (Exception e) { } return a > 1 ? 1 : 2; } }";
    const { arvore, no } = await raiz("java", t);
    // 1 + if + && + for + catch + ternário = 6
    expect(complexidadeDe(no, "java")).toBe(6);
    arvore.delete();
  });
});

describe("e_teste e e_gerado", () => {
  it("teste por caminho, nome e cabeçalho", () => {
    for (const c of ["src/a.test.ts", "src/a.spec.tsx", "tests/x.ts", "src/__tests__/y.ts", "pkg/test_a.py", "pkg/a_test.go", "src/ATest.java", "src/FooTests.cs", "spec/a_spec.rb"]) expect(ehArquivoDeTeste(c), c).toBe(true);
    for (const c of ["src/a.ts", "src/latest.ts", "src/contest.ts", "src/Atestado.java"]) expect(ehArquivoDeTeste(c), c).toBe(false);
    expect(ehArquivoDeTeste("src/x.tsx", "// @vitest-environment jsdom")).toBe(true);
  });

  it("gerado por nome e por cabeçalho", () => {
    expect(ehArquivoGerado("dist/app.min.js", "")).toBe(true);
    expect(ehArquivoGerado("api/x.pb.go", "")).toBe(true);
    expect(ehArquivoGerado("a.ts", "// @generated by tool\n")).toBe(true);
    expect(ehArquivoGerado("a.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n")).toBe(true);
    expect(ehArquivoGerado("a.cs", "// <auto-generated>\n")).toBe(true);
    expect(ehArquivoGerado("a.ts", "export const x = 1;\n")).toBe(false);
  });
});
