import { contextBridge, ipcRenderer, webUtils } from "electron";
import type { ApiAde, CanaisEvento } from "../compartilhado/ipc";

// Preload com sandbox: só pode usar `electron` (nenhum require relativo em runtime). Por isso os
// nomes de canal ficam INLINE aqui; `preload.test.ts` confere que batem com os de compartilhado/ipc.ts.
// API ENUMERADA — `ipcRenderer` cru nunca é exposto. Sem chamadas síncronas de IPC (bloqueariam a abertura).

type Ouvinte<T> = (e: T) => void;

function assinar<T>(canal: string, cb: Ouvinte<T>): () => void {
  const listener = (_evento: Electron.IpcRendererEvent, payload: T): void => cb(payload);
  ipcRenderer.on(canal, listener);
  return () => ipcRenderer.removeListener(canal, listener);
}

const api: ApiAde = {
  versao: () => ipcRenderer.invoke("app:versao") as Promise<string>,
  tema: {
    ler: () => ipcRenderer.invoke("app:tema_ler") as ReturnType<ApiAde["tema"]["ler"]>,
    definir: (preferencia) => ipcRenderer.invoke("app:tema_definir", { preferencia }) as ReturnType<ApiAde["tema"]["definir"]>,
    assinar: (cb) => assinar<CanaisEvento["app:tema_mudou"]>("app:tema_mudou", cb),
  },
  menu: {
    assinar: (cb) => assinar<CanaisEvento["app:menu"]>("app:menu", cb),
  },
  config: {
    ler: (chave) => ipcRenderer.invoke("app:config_ler", { chave }) as Promise<unknown>,
    gravar: (chave, valor) => ipcRenderer.invoke("app:config_gravar", { chave, valor }) as Promise<{ ok: true }>,
  },
  perf: {
    ler: () => ipcRenderer.invoke("app:perf") as ReturnType<ApiAde["perf"]["ler"]>,
    marcar: (nome) => {
      ipcRenderer.send("app:marca_perf", { nome });
    },
  },
  terminais: {
    listarFerramentas: (forcar = false) => ipcRenderer.invoke("terminais:listar_ferramentas", { forcar }) as ReturnType<ApiAde["terminais"]["listarFerramentas"]>,
    selecionarExecutavel: (ferramentaId) => ipcRenderer.invoke("terminais:selecionar_executavel", { ferramenta_id: ferramentaId }) as ReturnType<ApiAde["terminais"]["selecionarExecutavel"]>,
    abrir: (pedido) => ipcRenderer.invoke("terminais:abrir", pedido) as ReturnType<ApiAde["terminais"]["abrir"]>,
    listarSessoes: () => ipcRenderer.invoke("terminais:listar_sessoes") as ReturnType<ApiAde["terminais"]["listarSessoes"]>,
    recuperar: () => ipcRenderer.invoke("terminais:recuperar") as ReturnType<ApiAde["terminais"]["recuperar"]>,
    encerrar: (sessaoId) => ipcRenderer.invoke("terminais:encerrar", { sessao_id: sessaoId }) as Promise<boolean>,
    descartar: (sessaoId) => ipcRenderer.invoke("terminais:descartar", { sessao_id: sessaoId }) as Promise<boolean>,
    // teclado, redimensionar e interromper não esperam resposta; falhas voltam por assinarFalhas
    escrever: (sessaoId, dados) => {
      ipcRenderer.send("terminais:escrever", { sessao_id: sessaoId, dados });
    },
    redimensionar: (sessaoId, colunas, linhas) => {
      ipcRenderer.send("terminais:redimensionar", { sessao_id: sessaoId, colunas, linhas });
    },
    interromper: (sessaoId) => {
      ipcRenderer.send("terminais:interromper", { sessao_id: sessaoId });
    },
    confirmarConsumo: (sessaoId, bytes) => ipcRenderer.invoke("terminais:confirmar_consumo", { sessao_id: sessaoId, bytes }) as Promise<boolean>,
    anexar: (sessaoId, itens) => ipcRenderer.invoke("terminais:anexar", { sessao_id: sessaoId, itens }) as ReturnType<ApiAde["terminais"]["anexar"]>,
    caminhoDoArquivo: (arquivo) => {
      try {
        return webUtils.getPathForFile(arquivo);
      } catch {
        return "";
      }
    },
    abrirLink: (url) => ipcRenderer.invoke("terminais:abrir_link", { url }) as Promise<boolean>,
    lerLayout: (workspaceId) => ipcRenderer.invoke("terminais:layout_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["terminais"]["lerLayout"]>,
    gravarLayout: (workspaceId, layout) => ipcRenderer.invoke("terminais:layout_gravar", { workspace_id: workspaceId, layout }) as Promise<boolean>,
    diagnostico: () => ipcRenderer.invoke("terminais:diagnostico") as ReturnType<ApiAde["terminais"]["diagnostico"]>,
    conversas: () => ipcRenderer.invoke("terminais:conversas") as Promise<Record<string, string>>,
    assinarEventos: (cb) => assinar<CanaisEvento["terminais:evento"]>("terminais:evento", cb),
    assinarFalhas: (cb) => assinar<CanaisEvento["terminais:falha"]>("terminais:falha", cb),
  },
  workspaces: {
    estado: () => ipcRenderer.invoke("workspaces:estado") as ReturnType<ApiAde["workspaces"]["estado"]>,
    abrir: (caminho) => ipcRenderer.invoke("workspaces:abrir", { caminho }) as ReturnType<ApiAde["workspaces"]["abrir"]>,
    definirAtual: (workspaceId) => ipcRenderer.invoke("workspaces:definir_atual", { workspace_id: workspaceId }) as ReturnType<ApiAde["workspaces"]["definirAtual"]>,
    remover: (workspaceId) => ipcRenderer.invoke("workspaces:remover", { workspace_id: workspaceId }) as Promise<boolean>,
    definirPermissao: (workspaceId, permissao) => ipcRenderer.invoke("workspaces:definir_permissao", { workspace_id: workspaceId, permissao }) as ReturnType<ApiAde["workspaces"]["definirPermissao"]>,
    worktrees: (workspaceId) => ipcRenderer.invoke("workspaces:worktrees", { workspace_id: workspaceId }) as ReturnType<ApiAde["workspaces"]["worktrees"]>,
    assinar: (cb) => assinar<CanaisEvento["workspaces:mudou"]>("workspaces:mudou", cb),
    resumo: () => ipcRenderer.invoke("workspaces:resumo") as ReturnType<ApiAde["workspaces"]["resumo"]>,
    ativarResumo: (ativo) => ipcRenderer.invoke("workspaces:resumo_ativar", { ativo }) as ReturnType<ApiAde["workspaces"]["ativarResumo"]>,
    encerrarAgente: (workspaceId, sessaoId) => ipcRenderer.invoke("workspaces:encerrar_agente", { workspace_id: workspaceId, sessao_id: sessaoId }) as ReturnType<ApiAde["workspaces"]["encerrarAgente"]>,
    revelar: (workspaceId) => ipcRenderer.invoke("workspaces:revelar", { workspace_id: workspaceId }) as ReturnType<ApiAde["workspaces"]["revelar"]>,
    copiarCaminho: (workspaceId) => ipcRenderer.invoke("workspaces:copiar_caminho", { workspace_id: workspaceId }) as ReturnType<ApiAde["workspaces"]["copiarCaminho"]>,
    assinarResumo: (cb) => assinar<CanaisEvento["workspaces:resumo_mudou"]>("workspaces:resumo_mudou", cb),
    adicionarDestinoPadrao: () => ipcRenderer.invoke("workspaces:adicionar_destino_padrao") as ReturnType<ApiAde["workspaces"]["adicionarDestinoPadrao"]>,
    adicionarEscolherPasta: (lembrar) => ipcRenderer.invoke("workspaces:adicionar_escolher_pasta", { lembrar }) as ReturnType<ApiAde["workspaces"]["adicionarEscolherPasta"]>,
    adicionarAvaliarDestino: (p) => ipcRenderer.invoke("workspaces:adicionar_avaliar_destino", p) as ReturnType<ApiAde["workspaces"]["adicionarAvaliarDestino"]>,
    adicionarAbrirDestino: (p) => ipcRenderer.invoke("workspaces:adicionar_abrir_destino", p) as ReturnType<ApiAde["workspaces"]["adicionarAbrirDestino"]>,
    adicionarClonar: (p) => ipcRenderer.invoke("workspaces:adicionar_clonar_iniciar", p) as ReturnType<ApiAde["workspaces"]["adicionarClonar"]>,
    adicionarCancelarClone: (cloneId) => ipcRenderer.invoke("workspaces:adicionar_clonar_cancelar", { clone_id: cloneId }) as ReturnType<ApiAde["workspaces"]["adicionarCancelarClone"]>,
    adicionarBuscarProjetos: () => ipcRenderer.invoke("workspaces:adicionar_projetos_buscar") as ReturnType<ApiAde["workspaces"]["adicionarBuscarProjetos"]>,
    adicionarCancelarBusca: (buscaId) => ipcRenderer.invoke("workspaces:adicionar_projetos_cancelar", { busca_id: buscaId }) as ReturnType<ApiAde["workspaces"]["adicionarCancelarBusca"]>,
    adicionarProjetoAchado: (achadoId) => ipcRenderer.invoke("workspaces:adicionar_projeto_achado", { achado_id: achadoId }) as ReturnType<ApiAde["workspaces"]["adicionarProjetoAchado"]>,
    adicionarGhEstado: (forcar = false) => ipcRenderer.invoke("workspaces:adicionar_gh_estado", { forcar }) as ReturnType<ApiAde["workspaces"]["adicionarGhEstado"]>,
    adicionarListarRepos: (consentimento) => ipcRenderer.invoke("workspaces:adicionar_repos_listar", { consentimento }) as ReturnType<ApiAde["workspaces"]["adicionarListarRepos"]>,
    adicionarNovo: (p) => ipcRenderer.invoke("workspaces:adicionar_novo_criar", p) as ReturnType<ApiAde["workspaces"]["adicionarNovo"]>,
    assinarAdicionarProgresso: (cb) => assinar<CanaisEvento["workspaces:adicionar_progresso"]>("workspaces:adicionar_progresso", cb),
    assinarAdicionarProjetos: (cb) => assinar<CanaisEvento["workspaces:adicionar_projetos_lote"]>("workspaces:adicionar_projetos_lote", cb),
  },
  provedores: {
    listar: (forcar = false) => ipcRenderer.invoke("provedores:listar", { forcar }) as ReturnType<ApiAde["provedores"]["listar"]>,
    criarConta: (provedor, rotulo) => ipcRenderer.invoke("provedores:contas_criar", { provedor, rotulo }) as ReturnType<ApiAde["provedores"]["criarConta"]>,
    habilitarConta: (contaId, habilitada) => ipcRenderer.invoke("provedores:contas_habilitar", { conta_id: contaId, habilitada }) as ReturnType<ApiAde["provedores"]["habilitarConta"]>,
    diagnostico: () => ipcRenderer.invoke("provedores:diagnostico") as ReturnType<ApiAde["provedores"]["diagnostico"]>,
  },
  missoes: {
    listar: (workspaceId, estado = null, depois = null) => ipcRenderer.invoke("missoes:listar", { workspace_id: workspaceId, estado, depois }) as ReturnType<ApiAde["missoes"]["listar"]>,
    criar: (pedido) => ipcRenderer.invoke("missoes:criar", pedido) as ReturnType<ApiAde["missoes"]["criar"]>,
    detalhe: (missionId) => ipcRenderer.invoke("missoes:detalhe", { mission_id: missionId }) as ReturnType<ApiAde["missoes"]["detalhe"]>,
    encerrar: (missionId) => ipcRenderer.invoke("missoes:encerrar", { mission_id: missionId }) as ReturnType<ApiAde["missoes"]["encerrar"]>,
    abortar: (missionId) => ipcRenderer.invoke("missoes:abortar", { mission_id: missionId }) as ReturnType<ApiAde["missoes"]["abortar"]>,
    portoes: (missionId) => ipcRenderer.invoke("missoes:portoes", { mission_id: missionId }) as ReturnType<ApiAde["missoes"]["portoes"]>,
    liberarPortao: (missionId, portao) => ipcRenderer.invoke("missoes:liberar_portao", { mission_id: missionId, portao }) as ReturnType<ApiAde["missoes"]["liberarPortao"]>,
    assinar: (cb) => assinar<CanaisEvento["missoes:mudou"]>("missoes:mudou", cb),
  },
  metodo: {
    estado: (workspaceId) => ipcRenderer.invoke("metodo:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["metodo"]["estado"]>,
    rastro: (workspaceId, trabalhoId, depois = 0) => ipcRenderer.invoke("metodo:rastro", { workspace_id: workspaceId, trabalho_id: trabalhoId, depois }) as ReturnType<ApiAde["metodo"]["rastro"]>,
    comandoSugerido: (workspaceId, trabalhoId, gesto, argumento = null) => ipcRenderer.invoke("metodo:comando_sugerido", { workspace_id: workspaceId, trabalho_id: trabalhoId, gesto, argumento }) as ReturnType<ApiAde["metodo"]["comandoSugerido"]>,
    disparar: (pedido) => ipcRenderer.invoke("metodo:disparar", pedido) as ReturnType<ApiAde["metodo"]["disparar"]>,
    assinar: (cb) => assinar<CanaisEvento["metodo:mudou"]>("metodo:mudou", cb),
  },
  limites: {
    snapshot: (contaIds) => ipcRenderer.invoke("limites:snapshot", { conta_ids: contaIds }) as ReturnType<ApiAde["limites"]["snapshot"]>,
    atualizar: (contaId) => ipcRenderer.invoke("limites:atualizar", { conta_id: contaId }) as ReturnType<ApiAde["limites"]["atualizar"]>,
    definirManual: (contaId, janela, usadoPct, reiniciaEm) => ipcRenderer.invoke("limites:manual_definir", { conta_id: contaId, janela, usado_pct: usadoPct, reinicia_em: reiniciaEm }) as ReturnType<ApiAde["limites"]["definirManual"]>,
    limparManual: (contaId, janela) => ipcRenderer.invoke("limites:manual_limpar", { conta_id: contaId, janela }) as ReturnType<ApiAde["limites"]["limparManual"]>,
    historico: (pedido) => ipcRenderer.invoke("limites:historico", pedido) as ReturnType<ApiAde["limites"]["historico"]>,
    previsao: (contaId) => ipcRenderer.invoke("limites:previsao", { conta_id: contaId }) as ReturnType<ApiAde["limites"]["previsao"]>,
    eficiencia: (semanas, contaId) => ipcRenderer.invoke("limites:eficiencia", { conta_id: contaId, semanas }) as ReturnType<ApiAde["limites"]["eficiencia"]>,
    alertas: () => ipcRenderer.invoke("limites:alertas", {}) as ReturnType<ApiAde["limites"]["alertas"]>,
    assinar: (cb) => assinar<CanaisEvento["limites:evento"]>("limites:evento", cb),
  },
  harness: {
    lerConfig: (workspaceId) => ipcRenderer.invoke("harness:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["harness"]["lerConfig"]>,
    gravarConfig: (config) => ipcRenderer.invoke("harness:config_gravar", config) as ReturnType<ApiAde["harness"]["gravarConfig"]>,
    listarTaskTypes: () => ipcRenderer.invoke("harness:task_types_listar", {}) as ReturnType<ApiAde["harness"]["listarTaskTypes"]>,
    gravarTaskType: (tipo) => ipcRenderer.invoke("harness:task_types_gravar", tipo) as ReturnType<ApiAde["harness"]["gravarTaskType"]>,
    apagarTaskType: (slug) => ipcRenderer.invoke("harness:task_types_apagar", { slug }) as Promise<boolean>,
    listarPoliticas: (workspaceId) => ipcRenderer.invoke("harness:politica_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["harness"]["listarPoliticas"]>,
    gravarPolitica: (politica) => ipcRenderer.invoke("harness:politica_gravar", politica) as ReturnType<ApiAde["harness"]["gravarPolitica"]>,
    restaurarSemente: (workspaceId, taskType) => ipcRenderer.invoke("harness:politica_restaurar_semente", { workspace_id: workspaceId, task_type: taskType }) as ReturnType<ApiAde["harness"]["restaurarSemente"]>,
    lerEquivalencia: () => ipcRenderer.invoke("harness:equivalencia_ler", {}) as ReturnType<ApiAde["harness"]["lerEquivalencia"]>,
    gravarEquivalencia: (provedores) => ipcRenderer.invoke("harness:equivalencia_gravar", { provedores }) as ReturnType<ApiAde["harness"]["gravarEquivalencia"]>,
    restaurarEquivalencia: () => ipcRenderer.invoke("harness:equivalencia_restaurar", {}) as ReturnType<ApiAde["harness"]["restaurarEquivalencia"]>,
    recomendar: (workspaceId, descricao) => ipcRenderer.invoke("harness:recomendar", { workspace_id: workspaceId, descricao }) as ReturnType<ApiAde["harness"]["recomendar"]>,
    listarDecisoes: (pedido = {}) => ipcRenderer.invoke("harness:decisoes_listar", pedido) as ReturnType<ApiAde["harness"]["listarDecisoes"]>,
    listarContasConfig: () => ipcRenderer.invoke("harness:contas_config_listar", {}) as ReturnType<ApiAde["harness"]["listarContasConfig"]>,
    gravarContaConfig: (config) => ipcRenderer.invoke("harness:contas_config_gravar", config) as ReturnType<ApiAde["harness"]["gravarContaConfig"]>,
    listarTrocas: (pedido = {}) => ipcRenderer.invoke("harness:trocas_listar", pedido) as ReturnType<ApiAde["harness"]["listarTrocas"]>,
    decidirTroca: (trocaId, acao) => ipcRenderer.invoke("harness:troca_decidir", { troca_id: trocaId, acao }) as ReturnType<ApiAde["harness"]["decidirTroca"]>,
    moverPane: (paneId, contaAlvoId) => ipcRenderer.invoke("harness:mover_pane", { pane_id: paneId, conta_alvo_id: contaAlvoId }) as ReturnType<ApiAde["harness"]["moverPane"]>,
    lerDecisor: () => ipcRenderer.invoke("harness:decisor_ler", {}) as ReturnType<ApiAde["harness"]["lerDecisor"]>,
    gravarDecisor: (config) => ipcRenderer.invoke("harness:decisor_gravar", config) as ReturnType<ApiAde["harness"]["gravarDecisor"]>,
    testarDecisor: (chave) => ipcRenderer.invoke("harness:decisor_testar", { chave }) as ReturnType<ApiAde["harness"]["testarDecisor"]>,
    classificarIntencao: (texto, contexto) => ipcRenderer.invoke("harness:classificar_intencao", { texto, contexto }) as ReturnType<ApiAde["harness"]["classificarIntencao"]>,
    resolverPerfil: (pedido) => ipcRenderer.invoke("harness:resolver_perfil", pedido) as ReturnType<ApiAde["harness"]["resolverPerfil"]>,
    assinar: (cb) => assinar<CanaisEvento["harness:evento"]>("harness:evento", cb),
  },
  openrouter: {
    estado: () => ipcRenderer.invoke("provedores:openrouter_estado", {}) as ReturnType<ApiAde["openrouter"]["estado"]>,
    consentir: (versaoTexto) => ipcRenderer.invoke("provedores:openrouter_consentir", { consentimento: true, versao_texto: versaoTexto }) as ReturnType<ApiAde["openrouter"]["consentir"]>,
    revogar: () => ipcRenderer.invoke("provedores:openrouter_revogar", {}) as ReturnType<ApiAde["openrouter"]["revogar"]>,
    gravarChave: (rotulo, chave, contaId) => ipcRenderer.invoke("provedores:openrouter_chave_gravar", { conta_id: contaId, rotulo, chave }) as ReturnType<ApiAde["openrouter"]["gravarChave"]>,
    apagarChave: (contaId) => ipcRenderer.invoke("provedores:openrouter_chave_apagar", { conta_id: contaId }) as Promise<boolean>,
    testar: (pedido) => ipcRenderer.invoke("provedores:openrouter_testar", pedido) as ReturnType<ApiAde["openrouter"]["testar"]>,
    atualizarModelos: (contaId) => ipcRenderer.invoke("provedores:openrouter_modelos_atualizar", { conta_id: contaId }) as ReturnType<ApiAde["openrouter"]["atualizarModelos"]>,
    listarModelos: (pedido = {}) => ipcRenderer.invoke("provedores:openrouter_modelos_listar", pedido) as ReturnType<ApiAde["openrouter"]["listarModelos"]>,
    gravarModelo: (pedido) => ipcRenderer.invoke("provedores:openrouter_modelo_gravar", pedido) as ReturnType<ApiAde["openrouter"]["gravarModelo"]>,
    atualizarSaldo: (contaId) => ipcRenderer.invoke("provedores:openrouter_saldo_atualizar", { conta_id: contaId }) as ReturnType<ApiAde["openrouter"]["atualizarSaldo"]>,
  },
  cofre: {
    disponivel: () => ipcRenderer.invoke("cofre:disponivel", {}) as ReturnType<ApiAde["cofre"]["disponivel"]>,
    listar: () => ipcRenderer.invoke("cofre:listar", {}) as ReturnType<ApiAde["cofre"]["listar"]>,
    gravar: (pedido) => ipcRenderer.invoke("cofre:gravar", pedido) as ReturnType<ApiAde["cofre"]["gravar"]>,
    apagar: (id) => ipcRenderer.invoke("cofre:apagar", { id }) as Promise<boolean>,
    definirSenhaMestra: (senha) => ipcRenderer.invoke("cofre:senha_mestra_definir", { senha }) as ReturnType<ApiAde["cofre"]["definirSenhaMestra"]>,
    desbloquear: (senha) => ipcRenderer.invoke("cofre:desbloquear", { senha }) as ReturnType<ApiAde["cofre"]["desbloquear"]>,
    bloquear: () => ipcRenderer.invoke("cofre:bloquear", {}) as ReturnType<ApiAde["cofre"]["bloquear"]>,
  },
  squads: {
    listar: (pedido = {}) => ipcRenderer.invoke("squads:listar", pedido) as ReturnType<ApiAde["squads"]["listar"]>,
    obter: (slug) => ipcRenderer.invoke("squads:obter", { slug }) as ReturnType<ApiAde["squads"]["obter"]>,
    gravar: (pedido) => ipcRenderer.invoke("squads:gravar", pedido) as ReturnType<ApiAde["squads"]["gravar"]>,
    validar: (squad, workspaceId = null) => ipcRenderer.invoke("squads:validar", { squad, workspace_id: workspaceId }) as ReturnType<ApiAde["squads"]["validar"]>,
    duplicar: (pedido) => ipcRenderer.invoke("squads:duplicar", pedido) as ReturnType<ApiAde["squads"]["duplicar"]>,
    apagar: (slug, confirmarSlug) => ipcRenderer.invoke("squads:apagar", { slug, confirmar_slug: confirmarSlug }) as ReturnType<ApiAde["squads"]["apagar"]>,
    fabricaAtualizacao: (slug) => ipcRenderer.invoke("squads:fabrica_atualizacao", { slug }) as ReturnType<ApiAde["squads"]["fabricaAtualizacao"]>,
    fabricaAplicar: (slug, membros, sobrescreverEditados) => ipcRenderer.invoke("squads:fabrica_aplicar", sobrescreverEditados === undefined || sobrescreverEditados.length === 0 ? { slug, membros } : { slug, membros, sobrescrever_editados: sobrescreverEditados }) as ReturnType<ApiAde["squads"]["fabricaAplicar"]>,
    fabricaDiff: (pedido) => ipcRenderer.invoke("squads:fabrica_diff", pedido) as ReturnType<ApiAde["squads"]["fabricaDiff"]>,
    listarLixeira: () => ipcRenderer.invoke("squads:lixeira_listar", {}) as ReturnType<ApiAde["squads"]["listarLixeira"]>,
    restaurarDaLixeira: (nome) => ipcRenderer.invoke("squads:lixeira_restaurar", { nome }) as ReturnType<ApiAde["squads"]["restaurarDaLixeira"]>,
    lerArquivoDaExecucao: (pedido) => ipcRenderer.invoke("squads:execucao_arquivo", pedido) as ReturnType<ApiAde["squads"]["lerArquivoDaExecucao"]>,
    preflight: (slug, workspaceId) => ipcRenderer.invoke("squads:preflight", { slug, workspace_id: workspaceId }) as ReturnType<ApiAde["squads"]["preflight"]>,
    enviarPrompt: (pedido) => ipcRenderer.invoke("squads:enviar_prompt", pedido) as ReturnType<ApiAde["squads"]["enviarPrompt"]>,
    listarExecucoes: (pedido) => ipcRenderer.invoke("squads:execucoes_listar", pedido) as ReturnType<ApiAde["squads"]["listarExecucoes"]>,
    exportar: (pedido) => ipcRenderer.invoke("squads:exportar", pedido) as ReturnType<ApiAde["squads"]["exportar"]>,
    importarPrevia: (pedido) => ipcRenderer.invoke("squads:importar_previa", pedido) as ReturnType<ApiAde["squads"]["importarPrevia"]>,
    importarConfirmar: (previaId, slug) => ipcRenderer.invoke("squads:importar_confirmar", slug === undefined ? { previa_id: previaId } : { previa_id: previaId, slug }) as ReturnType<ApiAde["squads"]["importarConfirmar"]>,
    assinar: (cb) => assinar<CanaisEvento["squads:evento"]>("squads:evento", cb),
  },
  agentes: {
    listar: (squad) => ipcRenderer.invoke("agentes:listar", squad === undefined ? {} : { squad }) as ReturnType<ApiAde["agentes"]["listar"]>,
    lerPrompt: (agentId) => ipcRenderer.invoke("agentes:prompt_ler", { agent_id: agentId }) as ReturnType<ApiAde["agentes"]["lerPrompt"]>,
    gravarPrompt: (pedido) => ipcRenderer.invoke("agentes:prompt_gravar", pedido) as ReturnType<ApiAde["agentes"]["gravarPrompt"]>,
    previaPrompt: (pedido) => ipcRenderer.invoke("agentes:prompt_previa", pedido) as ReturnType<ApiAde["agentes"]["previaPrompt"]>,
    restaurarPrompt: (agentId) => ipcRenderer.invoke("agentes:prompt_restaurar", { agent_id: agentId }) as ReturnType<ApiAde["agentes"]["restaurarPrompt"]>,
    opcoesDePerfil: (cli) => ipcRenderer.invoke("agentes:perfil_opcoes", { cli }) as ReturnType<ApiAde["agentes"]["opcoesDePerfil"]>,
    abrirPane: (pedido) => ipcRenderer.invoke("agentes:abrir_pane", pedido) as ReturnType<ApiAde["agentes"]["abrirPane"]>,
  },
  painelLivre: {
    preferencia: (workspaceId, ativa, orquestradorEdita, fecharWorkers) => ipcRenderer.invoke("painel_livre:preferencia", { workspace_id: workspaceId, ...(ativa === undefined ? {} : { ativa }), ...(orquestradorEdita === undefined ? {} : { orquestrador_edita: orquestradorEdita }), ...(fecharWorkers === undefined ? {} : { fechar_workers: fecharWorkers }) }) as ReturnType<ApiAde["painelLivre"]["preferencia"]>,
    aprovacao: (pedido) => ipcRenderer.invoke("painel_livre:aprovacao", pedido) as ReturnType<ApiAde["painelLivre"]["aprovacao"]>,
    aprovacaoDoPane: (paneId) => ipcRenderer.invoke("painel_livre:aprovacao_pane", { pane_id: paneId }) as ReturnType<ApiAde["painelLivre"]["aprovacaoDoPane"]>,
    ponteGrok: (workspaceId, acao) => ipcRenderer.invoke("painel_livre:ponte_grok", { workspace_id: workspaceId, acao }) as ReturnType<ApiAde["painelLivre"]["ponteGrok"]>,
    abrir: (pedido) => ipcRenderer.invoke("painel_livre:abrir", pedido) as ReturnType<ApiAde["painelLivre"]["abrir"]>,
    orquestrar: (pedido) => ipcRenderer.invoke("painel_livre:orquestrar", pedido) as ReturnType<ApiAde["painelLivre"]["orquestrar"]>,
  },
  vcs: {
    estado: (alvo, ignorados = false) => ipcRenderer.invoke("vcs:estado", { ...alvo, ignorados }) as ReturnType<ApiAde["vcs"]["estado"]>,
    observar: (alvo, ativo) => ipcRenderer.invoke("vcs:observar", { ...alvo, ativo }) as ReturnType<ApiAde["vcs"]["observar"]>,
    diff: (pedido) => ipcRenderer.invoke("vcs:diff", pedido) as ReturnType<ApiAde["vcs"]["diff"]>,
    estagio: (alvo, op, args) => ipcRenderer.invoke("vcs:estagio", { ...alvo, ...args, op }) as never,
    commit: (alvo, op, args) => ipcRenderer.invoke("vcs:commit", { ...alvo, ...args, op }) as never,
    ramos: (alvo, op, args) => ipcRenderer.invoke("vcs:ramos", { ...alvo, ...args, op }) as never,
    stash: (alvo, op, args) => ipcRenderer.invoke("vcs:stash", { ...alvo, ...args, op }) as never,
    historico: (alvo, op, args) => ipcRenderer.invoke("vcs:historico", { ...alvo, ...args, op }) as never,
    remoto: (alvo, op, args) => ipcRenderer.invoke("vcs:remoto", { ...alvo, ...args, op }) as never,
    operacao: (alvo, op, args) => ipcRenderer.invoke("vcs:operacao", { ...alvo, ...args, op }) as never,
    conflitos: (alvo, op, args) => ipcRenderer.invoke("vcs:conflitos", { ...alvo, ...args, op }) as never,
    svn: (alvo, op, args) => ipcRenderer.invoke("vcs:svn", { ...alvo, ...args, op }) as never,
    forge: (alvo, op, args) => ipcRenderer.invoke("vcs:forge", { ...alvo, ...args, op }) as never,
    missao: (missionId, op, args) => ipcRenderer.invoke("vcs:missao", { mission_id: missionId, ...args, op }) as never,
    assinar: (cb) => assinar<CanaisEvento["vcs:mudou"]>("vcs:mudou", cb),
  },
  vcsPublicar: {
    estado: (workspaceId, consultarPr = false) => ipcRenderer.invoke("vcs:publicar_estado", { workspace_id: workspaceId, consultar_pr: consultarPr }) as ReturnType<ApiAde["vcsPublicar"]["estado"]>,
    prepararCommitPush: (workspaceId, sessaoFoco) => ipcRenderer.invoke("vcs:publicar_preparar_commit_push", { workspace_id: workspaceId, sessao_foco: sessaoFoco }) as ReturnType<ApiAde["vcsPublicar"]["prepararCommitPush"]>,
    prepararPr: (workspaceId, sessaoFoco) => ipcRenderer.invoke("vcs:publicar_preparar_pr", { workspace_id: workspaceId, sessao_foco: sessaoFoco }) as ReturnType<ApiAde["vcsPublicar"]["prepararPr"]>,
    enviarInstrucao: (pedido) => ipcRenderer.invoke("vcs:publicar_enviar_instrucao", pedido) as ReturnType<ApiAde["vcsPublicar"]["enviarInstrucao"]>,
    abrirUrl: (workspaceId, url) => ipcRenderer.invoke("vcs:publicar_abrir_url", { workspace_id: workspaceId, url }) as Promise<boolean>,
    buscarRemoto: (workspaceId, forcar) => ipcRenderer.invoke("vcs:publicar_buscar_remoto", { workspace_id: workspaceId, forcar }) as ReturnType<ApiAde["vcsPublicar"]["buscarRemoto"]>,
    prepararAtualizar: (workspaceId, sessaoFoco) => ipcRenderer.invoke("vcs:publicar_preparar_atualizar", { workspace_id: workspaceId, sessao_foco: sessaoFoco }) as ReturnType<ApiAde["vcsPublicar"]["prepararAtualizar"]>,
    atualizar: (workspaceId) => ipcRenderer.invoke("vcs:publicar_atualizar", { workspace_id: workspaceId }) as ReturnType<ApiAde["vcsPublicar"]["atualizar"]>,
    pedirMerge: (pedido) => ipcRenderer.invoke("vcs:publicar_pedir_merge", pedido) as ReturnType<ApiAde["vcsPublicar"]["pedirMerge"]>,
    ignorarSuite: (workspaceId) => ipcRenderer.invoke("vcs:publicar_ignorar_suite", { workspace_id: workspaceId }) as ReturnType<ApiAde["vcsPublicar"]["ignorarSuite"]>,
  },
  lojaMcp: {
    listar: () => ipcRenderer.invoke("loja_mcp:listar", {}) as ReturnType<ApiAde["lojaMcp"]["listar"]>,
    detalhe: (id, workspaceId = null) => ipcRenderer.invoke("loja_mcp:detalhe", { id, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["detalhe"]>,
    planoInstalacao: (ids, workspaceId = null) => ipcRenderer.invoke("loja_mcp:plano_instalacao", { ids, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["planoInstalacao"]>,
    instalar: (pedido) => ipcRenderer.invoke("loja_mcp:instalar", pedido) as ReturnType<ApiAde["lojaMcp"]["instalar"]>,
    cancelar: (instalacaoId) => ipcRenderer.invoke("loja_mcp:cancelar", { instalacao_id: instalacaoId }) as ReturnType<ApiAde["lojaMcp"]["cancelar"]>,
    desinstalar: (id, apagarSegredos) => ipcRenderer.invoke("loja_mcp:desinstalar", { id, apagar_segredos: apagarSegredos }) as ReturnType<ApiAde["lojaMcp"]["desinstalar"]>,
    planoAtualizacao: (id, workspaceId = null) => ipcRenderer.invoke("loja_mcp:plano_atualizacao", { id, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["planoAtualizacao"]>,
    atualizar: (id, consentimento, workspaceId = null) => ipcRenderer.invoke("loja_mcp:atualizar", { id, consentimento, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["atualizar"]>,
    variaveisEstado: (id) => ipcRenderer.invoke("loja_mcp:variaveis_estado", { id }) as ReturnType<ApiAde["lojaMcp"]["variaveisEstado"]>,
    gravarVariavel: (id, nome, valor) => ipcRenderer.invoke("loja_mcp:variavel_gravar", { id, nome, valor }) as ReturnType<ApiAde["lojaMcp"]["gravarVariavel"]>,
    apagarVariavel: (id, nome) => ipcRenderer.invoke("loja_mcp:variavel_apagar", { id, nome }) as ReturnType<ApiAde["lojaMcp"]["apagarVariavel"]>,
    testar: (id, workspaceId = null) => ipcRenderer.invoke("loja_mcp:testar", { id, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["testar"]>,
    habilitar: (id, alvoTipo, alvoValor, habilitado) => ipcRenderer.invoke("loja_mcp:habilitar", { id, alvo_tipo: alvoTipo, alvo_valor: alvoValor, habilitado }) as ReturnType<ApiAde["lojaMcp"]["habilitar"]>,
    habilitacoes: (workspaceId) => ipcRenderer.invoke("loja_mcp:habilitacoes", { workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["habilitacoes"]>,
    previaCliUsuario: (id, cli, workspaceId = null) => ipcRenderer.invoke("loja_mcp:previa_cli_usuario", { id, cli, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["previaCliUsuario"]>,
    instalarNaCli: (id, cli, confirmacao, workspaceId = null) => ipcRenderer.invoke("loja_mcp:instalar_na_cli", { id, cli, confirmacao, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["instalarNaCli"]>,
    removerDaCli: (id, cli) => ipcRenderer.invoke("loja_mcp:remover_da_cli", { id, cli }) as ReturnType<ApiAde["lojaMcp"]["removerDaCli"]>,
    logs: (id, limite = 50) => ipcRenderer.invoke("loja_mcp:logs", { id, limite }) as ReturnType<ApiAde["lojaMcp"]["logs"]>,
    kitEstado: () => ipcRenderer.invoke("loja_mcp:kit_estado", {}) as ReturnType<ApiAde["lojaMcp"]["kitEstado"]>,
    kitPlano: (workspaceId = null) => ipcRenderer.invoke("loja_mcp:kit_plano", { workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["kitPlano"]>,
    kitInstalar: (consentimento, workspaceId = null) => ipcRenderer.invoke("loja_mcp:kit_instalar", { consentimento, workspace_id: workspaceId }) as ReturnType<ApiAde["lojaMcp"]["kitInstalar"]>,
    kitOptOut: (valor) => ipcRenderer.invoke("loja_mcp:kit_opt_out", { valor }) as ReturnType<ApiAde["lojaMcp"]["kitOptOut"]>,
    diagnostico: () => ipcRenderer.invoke("loja_mcp:diagnostico", {}) as ReturnType<ApiAde["lojaMcp"]["diagnostico"]>,
    descobrir: (consulta) => ipcRenderer.invoke("loja_mcp:descobrir", { consulta }) as ReturnType<ApiAde["lojaMcp"]["descobrir"]>,
    assinar: (cb) => assinar<CanaisEvento["loja_mcp:evento"]>("loja_mcp:evento", cb),
  },
  catalogo: {
    varrer: (pedido) => ipcRenderer.invoke("catalogo:varrer", pedido) as ReturnType<ApiAde["catalogo"]["varrer"]>,
    listar: (pedido) => ipcRenderer.invoke("catalogo:listar", pedido) as ReturnType<ApiAde["catalogo"]["listar"]>,
    detalhe: (itemId) => ipcRenderer.invoke("catalogo:detalhe", { item_id: itemId }) as ReturnType<ApiAde["catalogo"]["detalhe"]>,
    instalar: (pedido) => ipcRenderer.invoke("catalogo:instalar", pedido) as ReturnType<ApiAde["catalogo"]["instalar"]>,
    desinstalar: (pedido) => ipcRenderer.invoke("catalogo:desinstalar", pedido) as ReturnType<ApiAde["catalogo"]["desinstalar"]>,
    limparAusentes: (tipo) => ipcRenderer.invoke("catalogo:limpar_ausentes", { tipo }) as ReturnType<ApiAde["catalogo"]["limparAusentes"]>,
    removerDoCatalogo: (itemId) => ipcRenderer.invoke("catalogo:remover_do_catalogo", { item_id: itemId }) as ReturnType<ApiAde["catalogo"]["removerDoCatalogo"]>,
    revelar: (pedido) => ipcRenderer.invoke("catalogo:revelar", pedido) as ReturnType<ApiAde["catalogo"]["revelar"]>,
    verificarMcp: (itemId, confirmado) => ipcRenderer.invoke("catalogo:verificar_mcp", { item_id: itemId, confirmado }) as ReturnType<ApiAde["catalogo"]["verificarMcp"]>,
    politicaLer: (workspaceId) => ipcRenderer.invoke("catalogo:politica_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["catalogo"]["politicaLer"]>,
    politicaGravar: (pedido) => ipcRenderer.invoke("catalogo:politica_gravar", pedido) as ReturnType<ApiAde["catalogo"]["politicaGravar"]>,
    politicaPrevia: (pedido) => ipcRenderer.invoke("catalogo:politica_previa", pedido) as ReturnType<ApiAde["catalogo"]["politicaPrevia"]>,
    saude: (workspaceId) => ipcRenderer.invoke("catalogo:saude", { workspace_id: workspaceId }) as ReturnType<ApiAde["catalogo"]["saude"]>,
    embarcadasEstado: () => ipcRenderer.invoke("catalogo:embarcadas_estado", {}) as ReturnType<ApiAde["catalogo"]["embarcadasEstado"]>,
    embarcadasInstalar: (nome, cli) => ipcRenderer.invoke("catalogo:embarcadas_instalar", { nome, cli }) as ReturnType<ApiAde["catalogo"]["embarcadasInstalar"]>,
    embarcadasOptOut: (nome, cli, valor) => ipcRenderer.invoke("catalogo:embarcadas_opt_out", { nome, cli, valor }) as ReturnType<ApiAde["catalogo"]["embarcadasOptOut"]>,
    assinar: (cb) => assinar<CanaisEvento["catalogo:evento"]>("catalogo:evento", cb),
  },
  gateway: {
    estado: () => ipcRenderer.invoke("gateway:estado", {}) as ReturnType<ApiAde["gateway"]["estado"]>,
    configLer: (workspaceId) => ipcRenderer.invoke("gateway:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["gateway"]["configLer"]>,
    configGravar: (pedido) => ipcRenderer.invoke("gateway:config_gravar", pedido) as ReturnType<ApiAde["gateway"]["configGravar"]>,
    ferramentas: (pedido) => ipcRenderer.invoke("gateway:ferramentas", pedido) as ReturnType<ApiAde["gateway"]["ferramentas"]>,
    filtroDefinir: (pedido) => ipcRenderer.invoke("gateway:filtro_definir", pedido) as ReturnType<ApiAde["gateway"]["filtroDefinir"]>,
    auditoria: (pedido) => ipcRenderer.invoke("gateway:auditoria", pedido) as ReturnType<ApiAde["gateway"]["auditoria"]>,
    revogarPane: (paneId) => ipcRenderer.invoke("gateway:revogar_pane", { pane_id: paneId }) as ReturnType<ApiAde["gateway"]["revogarPane"]>,
    assinar: (cb) => assinar<CanaisEvento["gateway:evento"]>("gateway:evento", cb),
  },
  memoria: {
    estado: (workspaceId) => ipcRenderer.invoke("memoria:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["memoria"]["estado"]>,
    gravarConfig: (pedido) => ipcRenderer.invoke("memoria:config_gravar", pedido) as ReturnType<ApiAde["memoria"]["gravarConfig"]>,
    definirMissao: (missionId, ativa) => ipcRenderer.invoke("memoria:missao_config", { mission_id: missionId, ativa }) as ReturnType<ApiAde["memoria"]["definirMissao"]>,
    listar: (pedido) => ipcRenderer.invoke("memoria:listar", pedido) as ReturnType<ApiAde["memoria"]["listar"]>,
    atualizar: (pedido) => ipcRenderer.invoke("memoria:atualizar", pedido) as ReturnType<ApiAde["memoria"]["atualizar"]>,
    esquecer: (entradaId) => ipcRenderer.invoke("memoria:esquecer", { entrada_id: entradaId }) as ReturnType<ApiAde["memoria"]["esquecer"]>,
    esquecerPane: (paneId) => ipcRenderer.invoke("memoria:esquecer_pane", { pane_id: paneId }) as ReturnType<ApiAde["memoria"]["esquecerPane"]>,
    purgar: (pedido) => ipcRenderer.invoke("memoria:purgar", pedido) as ReturnType<ApiAde["memoria"]["purgar"]>,
    exportar: (workspaceId, escopo) => ipcRenderer.invoke("memoria:exportar", { workspace_id: workspaceId, escopo }) as ReturnType<ApiAde["memoria"]["exportar"]>,
    briefPrevia: (paneId) => ipcRenderer.invoke("memoria:brief_previa", { pane_id: paneId }) as ReturnType<ApiAde["memoria"]["briefPrevia"]>,
    restaurar: (paneId, modo) => ipcRenderer.invoke("memoria:restaurar", { pane_id: paneId, modo }) as ReturnType<ApiAde["memoria"]["restaurar"]>,
    preferenciasListar: () => ipcRenderer.invoke("memoria:preferencias_listar", {}) as ReturnType<ApiAde["memoria"]["preferenciasListar"]>,
    preferenciasGravar: (pedido) => ipcRenderer.invoke("memoria:preferencias_gravar", pedido) as ReturnType<ApiAde["memoria"]["preferenciasGravar"]>,
    preferenciasRemover: (id) => ipcRenderer.invoke("memoria:preferencias_remover", { id }) as ReturnType<ApiAde["memoria"]["preferenciasRemover"]>,
    // um só `assinar` para os quatro eventos (canal + payload); os nomes ficam inline (sandbox) e o teste confere com o contrato
    assinar: (cb) => {
      const cancelar = [
        assinar<CanaisEvento["memoria:entrada_criada"]>("memoria:entrada_criada", (payload) => cb({ canal: "memoria:entrada_criada", payload })),
        assinar<CanaisEvento["memoria:brief_montado"]>("memoria:brief_montado", (payload) => cb({ canal: "memoria:brief_montado", payload })),
        assinar<CanaisEvento["memoria:restauracao_pedida"]>("memoria:restauracao_pedida", (payload) => cb({ canal: "memoria:restauracao_pedida", payload })),
        assinar<CanaisEvento["memoria:aviso"]>("memoria:aviso", (payload) => cb({ canal: "memoria:aviso", payload })),
      ];
      return () => {
        for (const c of cancelar) c();
      };
    },
  },
  maestro: {
    pedir: (pedido) => ipcRenderer.invoke("maestro:pedir", pedido) as ReturnType<ApiAde["maestro"]["pedir"]>,
    confirmar: (pedido) => ipcRenderer.invoke("maestro:confirmar", pedido) as ReturnType<ApiAde["maestro"]["confirmar"]>,
    cancelar: (id) => ipcRenderer.invoke("maestro:cancelar", { id }) as ReturnType<ApiAde["maestro"]["cancelar"]>,
    listarPipelines: (pedido) => ipcRenderer.invoke("maestro:pipelines_listar", pedido) as ReturnType<ApiAde["maestro"]["listarPipelines"]>,
    detalhe: (id) => ipcRenderer.invoke("maestro:pipeline_detalhe", { id }) as ReturnType<ApiAde["maestro"]["detalhe"]>,
    acao: (pedido) => ipcRenderer.invoke("maestro:pipeline_acao", pedido) as ReturnType<ApiAde["maestro"]["acao"]>,
    listarRecibos: (pedido) => ipcRenderer.invoke("maestro:recibos_listar", pedido) as ReturnType<ApiAde["maestro"]["listarRecibos"]>,
    lerConfig: (workspaceId) => ipcRenderer.invoke("maestro:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["maestro"]["lerConfig"]>,
    gravarConfig: (pedido) => ipcRenderer.invoke("maestro:config_gravar", pedido) as ReturnType<ApiAde["maestro"]["gravarConfig"]>,
    assinar: (cb) => assinar<CanaisEvento["maestro:evento"]>("maestro:evento", cb),
  },
  pipelines: {
    catalogo: () => ipcRenderer.invoke("pipelines:catalogo", {}) as ReturnType<ApiAde["pipelines"]["catalogo"]>,
    listarConfig: (workspaceId) => ipcRenderer.invoke("pipelines:config_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["pipelines"]["listarConfig"]>,
    gravarConfig: (pedido) => ipcRenderer.invoke("pipelines:config_gravar", pedido) as ReturnType<ApiAde["pipelines"]["gravarConfig"]>,
    restaurarConfig: (pedido) => ipcRenderer.invoke("pipelines:config_restaurar", pedido) as ReturnType<ApiAde["pipelines"]["restaurarConfig"]>,
    validar: (pedido) => ipcRenderer.invoke("pipelines:validar", pedido) as ReturnType<ApiAde["pipelines"]["validar"]>,
    perfisProntos: () => ipcRenderer.invoke("pipelines:perfis_prontos", {}) as ReturnType<ApiAde["pipelines"]["perfisProntos"]>,
    aplicarPronto: (pedido) => ipcRenderer.invoke("pipelines:aplicar_pronto", pedido) as ReturnType<ApiAde["pipelines"]["aplicarPronto"]>,
    exportar: (pedido) => ipcRenderer.invoke("pipelines:exportar", pedido) as ReturnType<ApiAde["pipelines"]["exportar"]>,
    importarPrevia: (pedido) => ipcRenderer.invoke("pipelines:importar_previa", pedido) as ReturnType<ApiAde["pipelines"]["importarPrevia"]>,
    importarConfirmar: (pedido) => ipcRenderer.invoke("pipelines:importar_confirmar", pedido) as ReturnType<ApiAde["pipelines"]["importarConfirmar"]>,
  },
  rigidez: {
    ler: (pedido) => ipcRenderer.invoke("rigidez:ler", pedido) as ReturnType<ApiAde["rigidez"]["ler"]>,
    definir: (pedido) => ipcRenderer.invoke("rigidez:definir", pedido) as ReturnType<ApiAde["rigidez"]["definir"]>,
    matriz: () => ipcRenderer.invoke("rigidez:matriz", {}) as ReturnType<ApiAde["rigidez"]["matriz"]>,
    previaPlano: (pedido) => ipcRenderer.invoke("rigidez:previa_plano", pedido) as ReturnType<ApiAde["rigidez"]["previaPlano"]>,
    hooksEstado: (pedido) => ipcRenderer.invoke("rigidez:hooks_estado", pedido) as ReturnType<ApiAde["rigidez"]["hooksEstado"]>,
    hooksReverter: (pedido) => ipcRenderer.invoke("rigidez:hooks_reverter", pedido) as ReturnType<ApiAde["rigidez"]["hooksReverter"]>,
    assinar: (cb) => assinar<CanaisEvento["rigidez:evento"]>("rigidez:evento", cb),
  },
  alertas: {
    catalogo: () => ipcRenderer.invoke("alertas:catalogo", {}) as ReturnType<ApiAde["alertas"]["catalogo"]>,
    listar: (f) => ipcRenderer.invoke("alertas:listar", f) as ReturnType<ApiAde["alertas"]["listar"]>,
    contar: () => ipcRenderer.invoke("alertas:contar", {}) as ReturnType<ApiAde["alertas"]["contar"]>,
    marcarLido: (ids) => ipcRenderer.invoke("alertas:marcar_lido", { ids }) as ReturnType<ApiAde["alertas"]["marcarLido"]>,
    marcarTodosLidos: (filtro) => ipcRenderer.invoke("alertas:marcar_lido", { todos: true, ...(filtro === undefined ? {} : { filtro }) }) as ReturnType<ApiAde["alertas"]["marcarTodosLidos"]>,
    silenciar: (alvo, ate) => ipcRenderer.invoke("alertas:silenciar", { alvo, ate }) as ReturnType<ApiAde["alertas"]["silenciar"]>,
    regrasListar: () => ipcRenderer.invoke("alertas:regras_listar", {}) as ReturnType<ApiAde["alertas"]["regrasListar"]>,
    regraGravar: (regra) => ipcRenderer.invoke("alertas:regra_gravar", regra) as ReturnType<ApiAde["alertas"]["regraGravar"]>,
    regraApagar: (id) => ipcRenderer.invoke("alertas:regra_apagar", { id }) as ReturnType<ApiAde["alertas"]["regraApagar"]>,
    regraPreset: (preset, canalId) => ipcRenderer.invoke("alertas:regra_preset", { preset, canal_id: canalId }) as ReturnType<ApiAde["alertas"]["regraPreset"]>,
    silencioLer: () => ipcRenderer.invoke("alertas:silencio_ler", {}) as ReturnType<ApiAde["alertas"]["silencioLer"]>,
    silencioGravar: (s) => ipcRenderer.invoke("alertas:silencio_gravar", s) as ReturnType<ApiAde["alertas"]["silencioGravar"]>,
    modelosListar: () => ipcRenderer.invoke("alertas:modelos_listar", {}) as ReturnType<ApiAde["alertas"]["modelosListar"]>,
    modeloGravar: (m) => ipcRenderer.invoke("alertas:modelo_gravar", m) as ReturnType<ApiAde["alertas"]["modeloGravar"]>,
    modeloRestaurar: (m) => ipcRenderer.invoke("alertas:modelo_restaurar", m) as ReturnType<ApiAde["alertas"]["modeloRestaurar"]>,
    modeloPrever: (m) => ipcRenderer.invoke("alertas:modelo_prever", m) as ReturnType<ApiAde["alertas"]["modeloPrever"]>,
    configLer: () => ipcRenderer.invoke("alertas:config_ler", {}) as ReturnType<ApiAde["alertas"]["configLer"]>,
    configGravar: (patch) => ipcRenderer.invoke("alertas:config_gravar", { patch }) as ReturnType<ApiAde["alertas"]["configGravar"]>,
    abrirEntidade: (alertaId) => ipcRenderer.invoke("alertas:abrir_entidade", { alerta_id: alertaId }) as ReturnType<ApiAde["alertas"]["abrirEntidade"]>,
    canais: {
      listar: () => ipcRenderer.invoke("canais:listar", {}) as ReturnType<ApiAde["alertas"]["canais"]["listar"]>,
      consentir: (canalId, versaoTexto, hashTexto) => ipcRenderer.invoke("canais:consentir", { canal_id: canalId, versao_texto: versaoTexto, hash_texto: hashTexto }) as ReturnType<ApiAde["alertas"]["canais"]["consentir"]>,
      ligarSaida: (canalId) => ipcRenderer.invoke("canais:ligar_saida", { canal_id: canalId }) as ReturnType<ApiAde["alertas"]["canais"]["ligarSaida"]>,
      desligarSaida: (canalId) => ipcRenderer.invoke("canais:desligar_saida", { canal_id: canalId }) as ReturnType<ApiAde["alertas"]["canais"]["desligarSaida"]>,
      testeEnvio: (canalId) => ipcRenderer.invoke("canais:teste_envio", { canal_id: canalId }) as ReturnType<ApiAde["alertas"]["canais"]["testeEnvio"]>,
    },
    telegram: {
      estado: () => ipcRenderer.invoke("telegram:estado", {}) as ReturnType<ApiAde["alertas"]["telegram"]["estado"]>,
      tokenTestar: (token) => ipcRenderer.invoke("telegram:token_testar", { token }) as ReturnType<ApiAde["alertas"]["telegram"]["tokenTestar"]>,
      tokenSalvar: (token) => ipcRenderer.invoke("telegram:token_salvar", { token }) as ReturnType<ApiAde["alertas"]["telegram"]["tokenSalvar"]>,
      tokenRemover: () => ipcRenderer.invoke("telegram:token_remover", {}) as ReturnType<ApiAde["alertas"]["telegram"]["tokenRemover"]>,
      webhookLimpar: () => ipcRenderer.invoke("telegram:webhook_limpar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["webhookLimpar"]>,
      comandosConfigurar: () => ipcRenderer.invoke("telegram:comandos_configurar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["comandosConfigurar"]>,
      parearIniciar: () => ipcRenderer.invoke("telegram:parear_iniciar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["parearIniciar"]>,
      parearCancelar: () => ipcRenderer.invoke("telegram:parear_cancelar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["parearCancelar"]>,
      parearDecidir: (pedidoId, permitir) => ipcRenderer.invoke("telegram:parear_decidir", { pedido_id: pedidoId, permitir }) as ReturnType<ApiAde["alertas"]["telegram"]["parearDecidir"]>,
      autorizadoConfig: (p) => ipcRenderer.invoke("telegram:autorizado_config", p) as ReturnType<ApiAde["alertas"]["telegram"]["autorizadoConfig"]>,
      autorizadoRevogar: (id) => ipcRenderer.invoke("telegram:autorizado_revogar", { id }) as ReturnType<ApiAde["alertas"]["telegram"]["autorizadoRevogar"]>,
      naoAutorizadoListar: () => ipcRenderer.invoke("telegram:nao_autorizado_listar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["naoAutorizadoListar"]>,
      naoAutorizadoBloquear: (userId) => ipcRenderer.invoke("telegram:nao_autorizado_bloquear", { user_id: userId }) as ReturnType<ApiAde["alertas"]["telegram"]["naoAutorizadoBloquear"]>,
      entradaLigar: (ligada) => ipcRenderer.invoke("telegram:entrada_ligar", { ligada }) as ReturnType<ApiAde["alertas"]["telegram"]["entradaLigar"]>,
      retomar: () => ipcRenderer.invoke("telegram:retomar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["retomar"]>,
      panico: (pararExecucoes) => ipcRenderer.invoke("telegram:panico", { parar_execucoes: pararExecucoes }) as ReturnType<ApiAde["alertas"]["telegram"]["panico"]>,
      planoDecidirDesktop: (p) => ipcRenderer.invoke("telegram:plano_decidir_desktop", p) as ReturnType<ApiAde["alertas"]["telegram"]["planoDecidirDesktop"]>,
      auditoriaListar: (depois, limite) => ipcRenderer.invoke("telegram:auditoria_listar", { depois, ...(limite === undefined ? {} : { limite }) }) as ReturnType<ApiAde["alertas"]["telegram"]["auditoriaListar"]>,
      auditoriaExportar: () => ipcRenderer.invoke("telegram:auditoria_exportar", {}) as ReturnType<ApiAde["alertas"]["telegram"]["auditoriaExportar"]>,
    },
    assinarNovo: (cb) => assinar<CanaisEvento["alertas:novo"]>("alertas:novo", (e) => cb(e.alerta)),
    assinarContagem: (cb) => assinar<CanaisEvento["alertas:contagem"]>("alertas:contagem", cb),
    assinarMudou: (cb) => assinar<CanaisEvento["alertas:mudou"]>("alertas:mudou", cb),
    assinarCanal: (cb) => assinar<CanaisEvento["canais:estado"]>("canais:estado", (e) => cb(e.canal)),
    assinarPareamento: (cb) => assinar<CanaisEvento["telegram:pareamento"]>("telegram:pareamento", cb),
    assinarTelegram: (cb) => assinar<CanaisEvento["telegram:evento"]>("telegram:evento", cb),
    assinarPlanoPendente: (cb) => assinar<CanaisEvento["telegram:plano_pendente_desktop"]>("telegram:plano_pendente_desktop", cb),
  },
  agil: {
    estado: (workspaceId) => ipcRenderer.invoke("agil:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["agil"]["estado"]>,
    configLer: (workspaceId) => ipcRenderer.invoke("agil:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["agil"]["configLer"]>,
    configGravar: (workspaceId, config) => ipcRenderer.invoke("agil:config_gravar", { workspace_id: workspaceId, config }) as ReturnType<ApiAde["agil"]["configGravar"]>,
    consentimentoIa: (workspaceId, consentido) => ipcRenderer.invoke("agil:consentimento_ia", { workspace_id: workspaceId, consentido }) as ReturnType<ApiAde["agil"]["consentimentoIa"]>,
    sincronizar: (workspaceId, forcar = false) => ipcRenderer.invoke("agil:sincronizar", { workspace_id: workspaceId, forcar }) as ReturnType<ApiAde["agil"]["sincronizar"]>,
    membroListar: (workspaceId) => ipcRenderer.invoke("agil:membro_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["agil"]["membroListar"]>,
    membroGravar: (workspaceId, membro) => ipcRenderer.invoke("agil:membro_gravar", { workspace_id: workspaceId, membro }) as ReturnType<ApiAde["agil"]["membroGravar"]>,
    backlogListar: (pedido) => ipcRenderer.invoke("agil:backlog_listar", pedido) as ReturnType<ApiAde["agil"]["backlogListar"]>,
    itemLer: (workspaceId, itemId) => ipcRenderer.invoke("agil:item_ler", { workspace_id: workspaceId, item_id: itemId }) as ReturnType<ApiAde["agil"]["itemLer"]>,
    itemCriar: (workspaceId, item) => ipcRenderer.invoke("agil:item_criar", { workspace_id: workspaceId, item }) as ReturnType<ApiAde["agil"]["itemCriar"]>,
    itemAtualizar: (workspaceId, itemId, campos) => ipcRenderer.invoke("agil:item_atualizar", { workspace_id: workspaceId, item_id: itemId, campos }) as ReturnType<ApiAde["agil"]["itemAtualizar"]>,
    itemDescartar: (workspaceId, itemId, motivo) => ipcRenderer.invoke("agil:item_descartar", { workspace_id: workspaceId, item_id: itemId, motivo }) as ReturnType<ApiAde["agil"]["itemDescartar"]>,
    itemReordenar: (workspaceId, itemId, antesId) => ipcRenderer.invoke("agil:item_reordenar", { workspace_id: workspaceId, item_id: itemId, antes_id: antesId }) as ReturnType<ApiAde["agil"]["itemReordenar"]>,
    itemPromover: (workspaceId, itemId, destino) => ipcRenderer.invoke("agil:item_promover", { workspace_id: workspaceId, item_id: itemId, destino }) as ReturnType<ApiAde["agil"]["itemPromover"]>,
    itemVincular: (workspaceId, itemId, trabalhoId, taskRef = null) => ipcRenderer.invoke("agil:item_vincular", { workspace_id: workspaceId, item_id: itemId, trabalho_id: trabalhoId, task_ref: taskRef }) as ReturnType<ApiAde["agil"]["itemVincular"]>,
    epicoListar: (workspaceId) => ipcRenderer.invoke("agil:epico_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["agil"]["epicoListar"]>,
    epicoGravar: (workspaceId, epico) => ipcRenderer.invoke("agil:epico_gravar", { workspace_id: workspaceId, ...epico }) as ReturnType<ApiAde["agil"]["epicoGravar"]>,
    epicoApagar: (workspaceId, epicoId) => ipcRenderer.invoke("agil:epico_apagar", { workspace_id: workspaceId, epico_id: epicoId }) as ReturnType<ApiAde["agil"]["epicoApagar"]>,
    estimar: (workspaceId, itemIds) => ipcRenderer.invoke("agil:estimar", { workspace_id: workspaceId, item_ids: itemIds }) as ReturnType<ApiAde["agil"]["estimar"]>,
    estimativaGravar: (workspaceId, pedido) => ipcRenderer.invoke("agil:estimativa_gravar", { workspace_id: workspaceId, ...pedido }) as ReturnType<ApiAde["agil"]["estimativaGravar"]>,
    classificacaoGravar: (workspaceId, pedido) => ipcRenderer.invoke("agil:classificacao_gravar", { workspace_id: workspaceId, ...pedido }) as ReturnType<ApiAde["agil"]["classificacaoGravar"]>,
    estimativaAceitarLote: (workspaceId, itemIds, confiancaMin) => ipcRenderer.invoke("agil:estimativa_aceitar_lote", { workspace_id: workspaceId, item_ids: itemIds, ...(confiancaMin === undefined ? {} : { confianca_min: confiancaMin }) }) as ReturnType<ApiAde["agil"]["estimativaAceitarLote"]>,
    sprintListar: (workspaceId) => ipcRenderer.invoke("agil:sprint_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["agil"]["sprintListar"]>,
    sprintCriar: (workspaceId, sprint) => ipcRenderer.invoke("agil:sprint_criar", { workspace_id: workspaceId, sprint }) as ReturnType<ApiAde["agil"]["sprintCriar"]>,
    sprintAtualizar: (workspaceId, sprintId, campos) => ipcRenderer.invoke("agil:sprint_atualizar", { workspace_id: workspaceId, sprint_id: sprintId, campos }) as ReturnType<ApiAde["agil"]["sprintAtualizar"]>,
    sprintIniciar: (workspaceId, sprintId) => ipcRenderer.invoke("agil:sprint_iniciar", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["sprintIniciar"]>,
    sprintCancelar: (workspaceId, sprintId) => ipcRenderer.invoke("agil:sprint_cancelar", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["sprintCancelar"]>,
    sprintItemMover: (workspaceId, sprintId, itemId, acao, motivo = null) => ipcRenderer.invoke("agil:sprint_item_mover", { workspace_id: workspaceId, sprint_id: sprintId, item_id: itemId, acao, motivo }) as ReturnType<ApiAde["agil"]["sprintItemMover"]>,
    sprintFechar: (workspaceId, sprintId, destino, versaoLancamento = null) => ipcRenderer.invoke("agil:sprint_fechar", { workspace_id: workspaceId, sprint_id: sprintId, destino_pendentes: destino, versao_lancamento: versaoLancamento }) as ReturnType<ApiAde["agil"]["sprintFechar"]>,
    capacidadeLer: (workspaceId, sprintId) => ipcRenderer.invoke("agil:capacidade_ler", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["capacidadeLer"]>,
    capacidadeGravar: (workspaceId, sprintId, membroId, ausenciasDias) => ipcRenderer.invoke("agil:capacidade_gravar", { workspace_id: workspaceId, sprint_id: sprintId, membro_id: membroId, ausencias_dias: ausenciasDias }) as ReturnType<ApiAde["agil"]["capacidadeGravar"]>,
    planejamentoSugerir: (workspaceId, sprintId, buffer) => ipcRenderer.invoke("agil:planejamento_sugerir", { workspace_id: workspaceId, sprint_id: sprintId, ...(buffer === undefined ? {} : { buffer }) }) as ReturnType<ApiAde["agil"]["planejamentoSugerir"]>,
    dailyGerar: (workspaceId, sprintId = null) => ipcRenderer.invoke("agil:daily_gerar", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["dailyGerar"]>,
    dailySalvar: (workspaceId, cerimoniaId, observacoes) => ipcRenderer.invoke("agil:daily_salvar", { workspace_id: workspaceId, cerimonia_id: cerimoniaId, observacoes }) as ReturnType<ApiAde["agil"]["dailySalvar"]>,
    reviewLer: (workspaceId, sprintId) => ipcRenderer.invoke("agil:review_ler", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["reviewLer"]>,
    reviewGravar: (workspaceId, sprintId, itemId, resultado, nota = null, devolver = false) => ipcRenderer.invoke("agil:review_gravar", { workspace_id: workspaceId, sprint_id: sprintId, item_id: itemId, resultado, nota, devolver }) as ReturnType<ApiAde["agil"]["reviewGravar"]>,
    retroLer: (workspaceId, sprintId) => ipcRenderer.invoke("agil:retro_ler", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["retroLer"]>,
    retroItemGravar: (workspaceId, cerimoniaId, pedido) => ipcRenderer.invoke("agil:retro_item_gravar", { workspace_id: workspaceId, cerimonia_id: cerimoniaId, ...pedido }) as ReturnType<ApiAde["agil"]["retroItemGravar"]>,
    retroAcaoGravar: (workspaceId, cerimoniaId, pedido) => ipcRenderer.invoke("agil:retro_acao_gravar", { workspace_id: workspaceId, cerimonia_id: cerimoniaId, ...pedido }) as ReturnType<ApiAde["agil"]["retroAcaoGravar"]>,
    retroAcaoParaItem: (workspaceId, acaoId) => ipcRenderer.invoke("agil:retro_acao_para_item", { workspace_id: workspaceId, acao_id: acaoId }) as ReturnType<ApiAde["agil"]["retroAcaoParaItem"]>,
    retrabalhoListar: (workspaceId, limite = 100) => ipcRenderer.invoke("agil:retrabalho_listar", { workspace_id: workspaceId, limite }) as ReturnType<ApiAde["agil"]["retrabalhoListar"]>,
    retrabalhoMarcar: (workspaceId, pedido) => ipcRenderer.invoke("agil:retrabalho_marcar", { workspace_id: workspaceId, ...pedido }) as ReturnType<ApiAde["agil"]["retrabalhoMarcar"]>,
    painel: (workspaceId, filtros = {}) => ipcRenderer.invoke("agil:painel", { workspace_id: workspaceId, filtros }) as ReturnType<ApiAde["agil"]["painel"]>,
    previsao: (workspaceId, filtros = {}, iteracoes) => ipcRenderer.invoke("agil:previsao", { workspace_id: workspaceId, filtros, ...(iteracoes === undefined ? {} : { iteracoes }) }) as ReturnType<ApiAde["agil"]["previsao"]>,
    praticas: (workspaceId, sprintId = null) => ipcRenderer.invoke("agil:praticas", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["agil"]["praticas"]>,
    checklistGravar: (workspaceId, sprintId, codigo, estado, nota = null) => ipcRenderer.invoke("agil:checklist_gravar", { workspace_id: workspaceId, sprint_id: sprintId, codigo, estado, nota }) as ReturnType<ApiAde["agil"]["checklistGravar"]>,
    exportar: (workspaceId, tipo, formato, escopo = {}) => ipcRenderer.invoke("agil:exportar", { workspace_id: workspaceId, tipo, formato, sprint_id: escopo.sprint_id ?? null }) as ReturnType<ApiAde["agil"]["exportar"]>,
    assinar: (cb) => assinar<CanaisEvento["agil:evento"]>("agil:evento", cb),
  },
  relatorios: {
    configLer: (workspaceId) => ipcRenderer.invoke("relatorios:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["relatorios"]["configLer"]>,
    configGravar: (workspaceId, config) => ipcRenderer.invoke("relatorios:config_gravar", { workspace_id: workspaceId, config }) as ReturnType<ApiAde["relatorios"]["configGravar"]>,
    consentimentoLlm: (workspaceId, consentido) => ipcRenderer.invoke("relatorios:consentimento_llm", { workspace_id: workspaceId, consentido }) as ReturnType<ApiAde["relatorios"]["consentimentoLlm"]>,
    sprints: (workspaceId) => ipcRenderer.invoke("relatorios:sprints", { workspace_id: workspaceId }) as ReturnType<ApiAde["relatorios"]["sprints"]>,
    listar: (workspaceId, filtros) => ipcRenderer.invoke("relatorios:listar", { workspace_id: workspaceId, ...(filtros === undefined ? {} : { filtros }) }) as ReturnType<ApiAde["relatorios"]["listar"]>,
    ler: (workspaceId, pacoteId) => ipcRenderer.invoke("relatorios:ler", { workspace_id: workspaceId, pacote_id: pacoteId }) as ReturnType<ApiAde["relatorios"]["ler"]>,
    gerar: (workspaceId, escopo, opcoes) => ipcRenderer.invoke("relatorios:gerar", { workspace_id: workspaceId, escopo, ...(opcoes === undefined ? {} : { opcoes }) }) as ReturnType<ApiAde["relatorios"]["gerar"]>,
    regenerar: (workspaceId, pacoteId) => ipcRenderer.invoke("relatorios:regenerar", { workspace_id: workspaceId, pacote_id: pacoteId }) as ReturnType<ApiAde["relatorios"]["regenerar"]>,
    previa: (workspaceId, pacoteId, nome) => ipcRenderer.invoke("relatorios:previa", { workspace_id: workspaceId, pacote_id: pacoteId, nome }) as ReturnType<ApiAde["relatorios"]["previa"]>,
    ajusteGravar: (workspaceId, sprintId, blocoId, textoMd) => ipcRenderer.invoke("relatorios:ajuste_gravar", { workspace_id: workspaceId, sprint_id: sprintId, bloco_id: blocoId, texto_md: textoMd }) as ReturnType<ApiAde["relatorios"]["ajusteGravar"]>,
    aprovar: (workspaceId, pacoteId, aprovar) => ipcRenderer.invoke("relatorios:aprovar", { workspace_id: workspaceId, pacote_id: pacoteId, aprovar }) as ReturnType<ApiAde["relatorios"]["aprovar"]>,
    exportar: (workspaceId, pacoteId, nomes, modo) => ipcRenderer.invoke("relatorios:exportar", { workspace_id: workspaceId, pacote_id: pacoteId, nomes, modo }) as ReturnType<ApiAde["relatorios"]["exportar"]>,
    divulgacaoEstado: (workspaceId) => ipcRenderer.invoke("relatorios:divulgacao_estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["relatorios"]["divulgacaoEstado"]>,
    consentimentoCanal: (workspaceId, canal, consentido) => ipcRenderer.invoke("relatorios:divulgacao_consentimento", { workspace_id: workspaceId, canal, consentido }) as ReturnType<ApiAde["relatorios"]["consentimentoCanal"]>,
    divulgacaoFila: (workspaceId, pacoteId) => ipcRenderer.invoke("relatorios:divulgacao_fila", { workspace_id: workspaceId, pacote_id: pacoteId }) as ReturnType<ApiAde["relatorios"]["divulgacaoFila"]>,
    divulgacaoEnfileirar: (workspaceId, pacoteId, canal, variante) => ipcRenderer.invoke("relatorios:divulgacao_enfileirar", { workspace_id: workspaceId, pacote_id: pacoteId, canal, variante }) as ReturnType<ApiAde["relatorios"]["divulgacaoEnfileirar"]>,
    divulgacaoAprovar: (workspaceId, envioId, aprovar) => ipcRenderer.invoke("relatorios:divulgacao_aprovar", { workspace_id: workspaceId, envio_id: envioId, aprovar }) as ReturnType<ApiAde["relatorios"]["divulgacaoAprovar"]>,
    divulgacaoEnviar: (workspaceId, envioId) => ipcRenderer.invoke("relatorios:divulgacao_enviar", { workspace_id: workspaceId, envio_id: envioId }) as ReturnType<ApiAde["relatorios"]["divulgacaoEnviar"]>,
    divulgacaoCancelar: (workspaceId, envioId) => ipcRenderer.invoke("relatorios:divulgacao_cancelar", { workspace_id: workspaceId, envio_id: envioId }) as ReturnType<ApiAde["relatorios"]["divulgacaoCancelar"]>,
    assinar: (cb) => assinar<CanaisEvento["relatorios:evento"]>("relatorios:evento", cb),
  },
  mapa: {
    resumo: (workspaceId) => ipcRenderer.invoke("mapa:resumo", { workspace_id: workspaceId }) as ReturnType<ApiAde["mapa"]["resumo"]>,
    analisar: (workspaceId, modo, historia) => ipcRenderer.invoke("mapa:analisar", { workspace_id: workspaceId, modo, ...(historia === undefined ? {} : { historia }) }) as ReturnType<ApiAde["mapa"]["analisar"]>,
    cancelar: (workspaceId) => ipcRenderer.invoke("mapa:cancelar", { workspace_id: workspaceId }) as ReturnType<ApiAde["mapa"]["cancelar"]>,
    apagar: (workspaceId, confirmacao) => ipcRenderer.invoke("mapa:apagar", { workspace_id: workspaceId, confirmacao }) as ReturnType<ApiAde["mapa"]["apagar"]>,
    grafo: (workspaceId, nivel, filtro, limite) => ipcRenderer.invoke("mapa:grafo", { workspace_id: workspaceId, nivel, ...(filtro === undefined ? {} : { filtro }), ...(limite === undefined ? {} : { limite }) }) as ReturnType<ApiAde["mapa"]["grafo"]>,
    vizinhos: (workspaceId, noId, direcao, profundidade, limite) => ipcRenderer.invoke("mapa:vizinhos", { workspace_id: workspaceId, no_id: noId, ...(direcao === undefined ? {} : { direcao }), ...(profundidade === undefined ? {} : { profundidade }), ...(limite === undefined ? {} : { limite }) }) as ReturnType<ApiAde["mapa"]["vizinhos"]>,
    no: (workspaceId, noId) => ipcRenderer.invoke("mapa:no", { workspace_id: workspaceId, no_id: noId }) as ReturnType<ApiAde["mapa"]["no"]>,
    fluxo: (workspaceId, entradaId, profundidade, minConfianca) => ipcRenderer.invoke("mapa:fluxo", { workspace_id: workspaceId, entrada_id: entradaId, ...(profundidade === undefined ? {} : { profundidade }), ...(minConfianca === undefined ? {} : { min_confianca: minConfianca }) }) as ReturnType<ApiAde["mapa"]["fluxo"]>,
    analise: ((workspaceId: string, tipo: string, parametros?: unknown) => ipcRenderer.invoke("mapa:analise", { workspace_id: workspaceId, tipo, ...(parametros === undefined ? {} : { parametros }) })) as ApiAde["mapa"]["analise"],
    raio: (workspaceId, arquivos, simbolos) => ipcRenderer.invoke("mapa:raio", { workspace_id: workspaceId, arquivos, ...(simbolos === undefined ? {} : { simbolos }) }) as ReturnType<ApiAde["mapa"]["raio"]>,
    perfil: (workspaceId) => ipcRenderer.invoke("mapa:perfil", { workspace_id: workspaceId }) as ReturnType<ApiAde["mapa"]["perfil"]>,
    buscar: (workspaceId, texto, tipos, limite) => ipcRenderer.invoke("mapa:buscar", { workspace_id: workspaceId, texto, ...(tipos === undefined ? {} : { tipos }), ...(limite === undefined ? {} : { limite }) }) as ReturnType<ApiAde["mapa"]["buscar"]>,
    exportar: (workspaceId, formato, vista, destino) => ipcRenderer.invoke("mapa:exportar", { workspace_id: workspaceId, formato, vista, ...(destino === undefined ? {} : { destino }) }) as ReturnType<ApiAde["mapa"]["exportar"]>,
    disparar: (workspaceId, pedido) => ipcRenderer.invoke("mapa:disparar", { workspace_id: workspaceId, ...pedido }) as ReturnType<ApiAde["mapa"]["disparar"]>,
    configLer: (workspaceId) => ipcRenderer.invoke("mapa:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["mapa"]["configLer"]>,
    configGravar: (workspaceId, parcial) => ipcRenderer.invoke("mapa:config_gravar", { workspace_id: workspaceId, config: parcial }) as ReturnType<ApiAde["mapa"]["configGravar"]>,
    layoutLer: (workspaceId, chave) => ipcRenderer.invoke("mapa:layout_ler", { workspace_id: workspaceId, chave }) as ReturnType<ApiAde["mapa"]["layoutLer"]>,
    layoutGravar: (workspaceId, chave, nivel, posicoes) => ipcRenderer.invoke("mapa:layout_gravar", { workspace_id: workspaceId, chave, nivel, posicoes }) as ReturnType<ApiAde["mapa"]["layoutGravar"]>,
    assinar: (cb) => assinar<CanaisEvento["mapa:evento"]>("mapa:evento", cb),
  },
  executar: {
    listar: (workspaceId) => ipcRenderer.invoke("executar:listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["executar"]["listar"]>,
    estado: (workspaceId) => ipcRenderer.invoke("executar:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["executar"]["estado"]>,
    iniciar: (workspaceId, configId, confirmarHash) => ipcRenderer.invoke("executar:iniciar", { workspace_id: workspaceId, ...(configId === undefined ? {} : { config_id: configId }), ...(confirmarHash === undefined ? {} : { confirmar_hash: confirmarHash }) }) as ReturnType<ApiAde["executar"]["iniciar"]>,
    parar: (workspaceId, configId) => ipcRenderer.invoke("executar:parar", { workspace_id: workspaceId, ...(configId === undefined ? {} : { config_id: configId }) }) as ReturnType<ApiAde["executar"]["parar"]>,
    reiniciar: (workspaceId, configId) => ipcRenderer.invoke("executar:reiniciar", { workspace_id: workspaceId, ...(configId === undefined ? {} : { config_id: configId }) }) as ReturnType<ApiAde["executar"]["reiniciar"]>,
    gravarConfig: (workspaceId, config, confirmouShell) => ipcRenderer.invoke("executar:config_gravar", { workspace_id: workspaceId, config, confirmou_shell: confirmouShell }) as ReturnType<ApiAde["executar"]["gravarConfig"]>,
    removerConfig: (workspaceId, configId) => ipcRenderer.invoke("executar:config_remover", { workspace_id: workspaceId, config_id: configId }) as ReturnType<ApiAde["executar"]["removerConfig"]>,
    definirPadrao: (workspaceId, configId) => ipcRenderer.invoke("executar:definir_padrao", { workspace_id: workspaceId, config_id: configId }) as ReturnType<ApiAde["executar"]["definirPadrao"]>,
    revogarConfianca: (workspaceId, configId) => ipcRenderer.invoke("executar:revogar_confianca", { workspace_id: workspaceId, ...(configId === undefined ? {} : { config_id: configId }) }) as ReturnType<ApiAde["executar"]["revogarConfianca"]>,
    historico: (workspaceId) => ipcRenderer.invoke("executar:historico", { workspace_id: workspaceId }) as ReturnType<ApiAde["executar"]["historico"]>,
    abrirUrl: (workspaceId) => ipcRenderer.invoke("executar:abrir_url", { workspace_id: workspaceId }) as ReturnType<ApiAde["executar"]["abrirUrl"]>,
    assinar: (cb) => assinar<CanaisEvento["executar:evento"]>("executar:evento", cb),
    assistentePrevia: (workspaceId, cli) => ipcRenderer.invoke("executar:assistente_previa", { workspace_id: workspaceId, ...(cli === undefined ? {} : { cli }) }) as ReturnType<ApiAde["executar"]["assistentePrevia"]>,
    assistentePropor: (workspaceId, cli, dossieHash, consentimento) => ipcRenderer.invoke("executar:assistente_propor", { workspace_id: workspaceId, cli, dossie_hash: dossieHash, consentimento }) as ReturnType<ApiAde["executar"]["assistentePropor"]>,
    assistenteCancelar: (workspaceId) => ipcRenderer.invoke("executar:assistente_cancelar", { workspace_id: workspaceId }) as ReturnType<ApiAde["executar"]["assistenteCancelar"]>,
    assistenteSalvar: (workspaceId, assistenteId, configs, padraoId) => ipcRenderer.invoke("executar:assistente_salvar", { workspace_id: workspaceId, assistente_id: assistenteId, configs, padrao_id: padraoId }) as ReturnType<ApiAde["executar"]["assistenteSalvar"]>,
    assistenteAssinar: (cb) => assinar<CanaisEvento["executar:assistente_evento"]>("executar:assistente_evento", cb),
  },
  custo: {
    resumo: (pedido) => ipcRenderer.invoke("custo:resumo", pedido) as ReturnType<ApiAde["custo"]["resumo"]>,
    relatorio: (pedido) => ipcRenderer.invoke("custo:relatorio", pedido) as ReturnType<ApiAde["custo"]["relatorio"]>,
    estimativa: (pedido = {}) => ipcRenderer.invoke("custo:estimativa", pedido) as ReturnType<ApiAde["custo"]["estimativa"]>,
    previsaoMissao: (missionId) => ipcRenderer.invoke("custo:previsao_missao", { mission_id: missionId }) as ReturnType<ApiAde["custo"]["previsaoMissao"]>,
    previsaoPeriodo: (workspaceId, inicio, fim) => ipcRenderer.invoke("custo:previsao_periodo", { workspace_id: workspaceId, inicio, fim }) as ReturnType<ApiAde["custo"]["previsaoPeriodo"]>,
    sprint: (workspaceId, sprintId) => ipcRenderer.invoke("custo:sprint", { workspace_id: workspaceId, sprint_id: sprintId }) as ReturnType<ApiAde["custo"]["sprint"]>,
    fontes: (workspaceId) => ipcRenderer.invoke("custo:fontes", workspaceId === undefined ? {} : { workspace_id: workspaceId }) as ReturnType<ApiAde["custo"]["fontes"]>,
    precosListar: () => ipcRenderer.invoke("custo:precos_listar", {}) as ReturnType<ApiAde["custo"]["precosListar"]>,
    precoGravar: (pedido) => ipcRenderer.invoke("custo:preco_gravar", pedido) as ReturnType<ApiAde["custo"]["precoGravar"]>,
    precoApagar: (id) => ipcRenderer.invoke("custo:preco_apagar", { id }) as ReturnType<ApiAde["custo"]["precoApagar"]>,
    reprecificar: (pedido = {}) => ipcRenderer.invoke("custo:reprecificar", pedido) as ReturnType<ApiAde["custo"]["reprecificar"]>,
    configLer: () => ipcRenderer.invoke("custo:config_ler", {}) as ReturnType<ApiAde["custo"]["configLer"]>,
    configGravar: (config) => ipcRenderer.invoke("custo:config_gravar", config) as ReturnType<ApiAde["custo"]["configGravar"]>,
    tetoGravar: (missionId, tetoUsd) => ipcRenderer.invoke("custo:teto_gravar", { mission_id: missionId, teto_usd: tetoUsd }) as ReturnType<ApiAde["custo"]["tetoGravar"]>,
    reindexar: (workspaceId) => ipcRenderer.invoke("custo:reindexar", workspaceId === undefined ? {} : { workspace_id: workspaceId }) as ReturnType<ApiAde["custo"]["reindexar"]>,
    diagnostico: () => ipcRenderer.invoke("custo:diagnostico", {}) as ReturnType<ApiAde["custo"]["diagnostico"]>,
    assinar: (cb) => assinar<CanaisEvento["custo:evento"]>("custo:evento", cb),
  },
  board: {
    snapshot: (filtros) => ipcRenderer.invoke("board:snapshot", { filtros }) as ReturnType<ApiAde["board"]["snapshot"]>,
    cardDetalhe: (pedido) => ipcRenderer.invoke("board:card_detalhe", pedido) as ReturnType<ApiAde["board"]["cardDetalhe"]>,
    abrirArquivo: (pedido) => ipcRenderer.invoke("board:abrir_arquivo", pedido) as ReturnType<ApiAde["board"]["abrirArquivo"]>,
    delegarCard: (pedido) => ipcRenderer.invoke("board:delegar_card", pedido) as ReturnType<ApiAde["board"]["delegarCard"]>,
    configLer: (workspaceId) => ipcRenderer.invoke("board:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["board"]["configLer"]>,
    configGravar: (workspaceId, config) => ipcRenderer.invoke("board:config_gravar", { workspace_id: workspaceId, config }) as ReturnType<ApiAde["board"]["configGravar"]>,
    assinar: (cb) => assinar<CanaisEvento["board:evento"]>("board:evento", cb),
  },
  conhecimento: {
    estado: (workspaceId) => ipcRenderer.invoke("conhecimento:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["conhecimento"]["estado"]>,
    lerConfig: (workspaceId) => ipcRenderer.invoke("conhecimento:config_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["conhecimento"]["lerConfig"]>,
    gravarConfig: (pedido) => ipcRenderer.invoke("conhecimento:config_gravar", pedido) as ReturnType<ApiAde["conhecimento"]["gravarConfig"]>,
    buscar: (pedido) => ipcRenderer.invoke("conhecimento:buscar", pedido) as ReturnType<ApiAde["conhecimento"]["buscar"]>,
    contextoPrevia: (pedido) => ipcRenderer.invoke("conhecimento:contexto_previa", pedido) as ReturnType<ApiAde["conhecimento"]["contextoPrevia"]>,
    listarDocumentos: (pedido) => ipcRenderer.invoke("conhecimento:documentos_listar", pedido) as ReturnType<ApiAde["conhecimento"]["listarDocumentos"]>,
    detalheDocumento: (workspaceId, documentoId) => ipcRenderer.invoke("conhecimento:documento_detalhe", { workspace_id: workspaceId, documento_id: documentoId }) as ReturnType<ApiAde["conhecimento"]["detalheDocumento"]>,
    reindexar: (workspaceId, fonte) => ipcRenderer.invoke("conhecimento:reindexar", { workspace_id: workspaceId, fonte }) as ReturnType<ApiAde["conhecimento"]["reindexar"]>,
    esquecer: (workspaceId, alvo) => ipcRenderer.invoke("conhecimento:esquecer", { workspace_id: workspaceId, alvo }) as ReturnType<ApiAde["conhecimento"]["esquecer"]>,
    purgar: (workspaceId, confirmacao) => ipcRenderer.invoke("conhecimento:purgar", { workspace_id: workspaceId, confirmacao }) as ReturnType<ApiAde["conhecimento"]["purgar"]>,
    importarHistorico: (workspaceId, cli) => ipcRenderer.invoke("conhecimento:importar_historico", { workspace_id: workspaceId, cli, consentimento: true }) as ReturnType<ApiAde["conhecimento"]["importarHistorico"]>,
    exportar: (workspaceId) => ipcRenderer.invoke("conhecimento:exportar", { workspace_id: workspaceId }) as ReturnType<ApiAde["conhecimento"]["exportar"]>,
    subgrafo: (pedido) => ipcRenderer.invoke("conhecimento:grafo_subgrafo", pedido) as ReturnType<ApiAde["conhecimento"]["subgrafo"]>,
    detalheNo: (workspaceId, noId) => ipcRenderer.invoke("conhecimento:grafo_no", { workspace_id: workspaceId, no_id: noId }) as ReturnType<ApiAde["conhecimento"]["detalheNo"]>,
    gravarPosicoes: (workspaceId, posicoes) => ipcRenderer.invoke("conhecimento:grafo_posicoes_gravar", { workspace_id: workspaceId, posicoes }) as ReturnType<ApiAde["conhecimento"]["gravarPosicoes"]>,
    listarAprendizados: (pedido) => ipcRenderer.invoke("conhecimento:aprendizados_listar", pedido) as ReturnType<ApiAde["conhecimento"]["listarAprendizados"]>,
    atualizarAprendizado: (pedido) => ipcRenderer.invoke("conhecimento:aprendizado_atualizar", pedido) as ReturnType<ApiAde["conhecimento"]["atualizarAprendizado"]>,
    feedback: (pedido) => ipcRenderer.invoke("conhecimento:feedback", pedido) as ReturnType<ApiAde["conhecimento"]["feedback"]>,
    destilarMissao: (workspaceId, missionId) => ipcRenderer.invoke("conhecimento:destilar_missao", { workspace_id: workspaceId, mission_id: missionId }) as ReturnType<ApiAde["conhecimento"]["destilarMissao"]>,
    modelos: (workspaceId) => ipcRenderer.invoke("conhecimento:modelos", { workspace_id: workspaceId }) as ReturnType<ApiAde["conhecimento"]["modelos"]>,
    definirModelo: (workspaceId, modelo) => ipcRenderer.invoke("conhecimento:modelo_definir", { workspace_id: workspaceId, modelo }) as ReturnType<ApiAde["conhecimento"]["definirModelo"]>,
    assinar: (cb) => {
      const desligar = [
        assinar<CanaisEvento["conhecimento:progresso"]>("conhecimento:progresso", (payload) => cb({ canal: "conhecimento:progresso", payload })),
        assinar<CanaisEvento["conhecimento:consultado"]>("conhecimento:consultado", (payload) => cb({ canal: "conhecimento:consultado", payload })),
        assinar<CanaisEvento["conhecimento:aprendizado_novo"]>("conhecimento:aprendizado_novo", (payload) => cb({ canal: "conhecimento:aprendizado_novo", payload })),
      ];
      return () => desligar.forEach((d) => d());
    },
  },
  chat: {
    listarConversas: (workspaceId) => ipcRenderer.invoke("chat:conversas_listar", { workspace_id: workspaceId }) as ReturnType<ApiAde["chat"]["listarConversas"]>,
    criarConversa: (pedido) => ipcRenderer.invoke("chat:conversa_criar", pedido) as ReturnType<ApiAde["chat"]["criarConversa"]>,
    lerConversa: (conversaId) => ipcRenderer.invoke("chat:conversa_ler", { conversa_id: conversaId }) as ReturnType<ApiAde["chat"]["lerConversa"]>,
    apagarConversa: (conversaId) => ipcRenderer.invoke("chat:conversa_apagar", { conversa_id: conversaId }) as ReturnType<ApiAde["chat"]["apagarConversa"]>,
    lerPerfil: (workspaceId) => ipcRenderer.invoke("chat:perfil_ler", { workspace_id: workspaceId }) as ReturnType<ApiAde["chat"]["lerPerfil"]>,
    gravarPerfil: (pedido) => ipcRenderer.invoke("chat:perfil_gravar", pedido) as ReturnType<ApiAde["chat"]["gravarPerfil"]>,
    enviar: (pedido) => ipcRenderer.invoke("chat:enviar", pedido) as ReturnType<ApiAde["chat"]["enviar"]>,
    parar: (mensagemId) => ipcRenderer.invoke("chat:parar", { mensagem_id: mensagemId }) as ReturnType<ApiAde["chat"]["parar"]>,
    decidirPlano: (pedido) => ipcRenderer.invoke("chat:plano_decidir", pedido) as ReturnType<ApiAde["chat"]["decidirPlano"]>,
    pararPlano: (planoId) => ipcRenderer.invoke("chat:plano_parar", { plano_id: planoId }) as ReturnType<ApiAde["chat"]["pararPlano"]>,
    assinar: (cb) => {
      const desligar = [
        assinar<CanaisEvento["chat:token"]>("chat:token", (payload) => cb({ canal: "chat:token", payload })),
        assinar<CanaisEvento["chat:mensagem"]>("chat:mensagem", (payload) => cb({ canal: "chat:mensagem", payload })),
        assinar<CanaisEvento["chat:plano"]>("chat:plano", (payload) => cb({ canal: "chat:plano", payload })),
        assinar<CanaisEvento["chat:progresso"]>("chat:progresso", (payload) => cb({ canal: "chat:progresso", payload })),
      ];
      return () => desligar.forEach((d) => d());
    },
  },
  rag: {
    estado: (workspaceId) => ipcRenderer.invoke("rag:backend_estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["rag"]["estado"]>,
    provedores: () => ipcRenderer.invoke("rag:backend_provedores", {}) as ReturnType<ApiAde["rag"]["provedores"]>,
    configurar: (pedido) => ipcRenderer.invoke("rag:backend_configurar", pedido) as ReturnType<ApiAde["rag"]["configurar"]>,
    testar: (pedido) => ipcRenderer.invoke("rag:backend_testar", pedido) as ReturnType<ApiAde["rag"]["testar"]>,
    esquecerSegredo: (provedor) => ipcRenderer.invoke("rag:backend_esquecer_segredo", { provedor }) as ReturnType<ApiAde["rag"]["esquecerSegredo"]>,
    previaMigracao: (workspaceId, tipos) => ipcRenderer.invoke("rag:migracao_previa", { workspace_id: workspaceId, tipos }) as ReturnType<ApiAde["rag"]["previaMigracao"]>,
    iniciarMigracao: (pedido) => ipcRenderer.invoke("rag:migracao_iniciar", pedido) as ReturnType<ApiAde["rag"]["iniciarMigracao"]>,
    pausarMigracao: (migracaoId) => ipcRenderer.invoke("rag:migracao_pausar", { migracao_id: migracaoId }) as ReturnType<ApiAde["rag"]["pausarMigracao"]>,
    retomarMigracao: (migracaoId) => ipcRenderer.invoke("rag:migracao_retomar", { migracao_id: migracaoId }) as ReturnType<ApiAde["rag"]["retomarMigracao"]>,
    cancelarMigracao: (migracaoId) => ipcRenderer.invoke("rag:migracao_cancelar", { migracao_id: migracaoId }) as ReturnType<ApiAde["rag"]["cancelarMigracao"]>,
    verificarMigracao: (migracaoId) => ipcRenderer.invoke("rag:migracao_verificar", { migracao_id: migracaoId }) as ReturnType<ApiAde["rag"]["verificarMigracao"]>,
    voltarParaLocal: (workspaceId, baixarDoRemoto) => ipcRenderer.invoke("rag:voltar_para_local", { workspace_id: workspaceId, baixar_do_remoto: baixarDoRemoto }) as ReturnType<ApiAde["rag"]["voltarParaLocal"]>,
    sincronizar: (workspaceId) => ipcRenderer.invoke("rag:sincronizar", { workspace_id: workspaceId }) as ReturnType<ApiAde["rag"]["sincronizar"]>,
    apagarRemoto: (workspaceId, confirmacao) => ipcRenderer.invoke("rag:remoto_apagar", { workspace_id: workspaceId, confirmacao }) as ReturnType<ApiAde["rag"]["apagarRemoto"]>,
    assinar: (cb) => {
      const desligar = [
        assinar<CanaisEvento["rag:migracao_progresso"]>("rag:migracao_progresso", (payload) => cb({ canal: "rag:migracao_progresso", payload })),
        assinar<CanaisEvento["rag:aviso"]>("rag:aviso", (payload) => cb({ canal: "rag:aviso", payload })),
      ];
      return () => desligar.forEach((d) => d());
    },
  },
  captura: {
    estado: () => ipcRenderer.invoke("captura:estado") as ReturnType<ApiAde["captura"]["estado"]>,
    configGravar: (patch) => ipcRenderer.invoke("captura:config_gravar", { patch }) as ReturnType<ApiAde["captura"]["configGravar"]>,
    pedirTela: () => ipcRenderer.invoke("captura:pedir_tela") as ReturnType<ApiAde["captura"]["pedirTela"]>,
    regiaoIniciar: (fonte) => ipcRenderer.invoke("captura:regiao_iniciar", { fonte }) as ReturnType<ApiAde["captura"]["regiaoIniciar"]>,
    regiaoConfirmar: (token, selecao, workspaceId) => ipcRenderer.invoke("captura:regiao_confirmar", { token, selecao, workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["regiaoConfirmar"]>,
    regiaoCancelar: (token) => ipcRenderer.invoke("captura:regiao_cancelar", { token }) as ReturnType<ApiAde["captura"]["regiaoCancelar"]>,
    janelaInteira: (workspaceId) => ipcRenderer.invoke("captura:janela_inteira", { workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["janelaInteira"]>,
    quadrosIniciar: (fonte, fps, workspaceId) => ipcRenderer.invoke("captura:quadros_iniciar", { fonte, fps, workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["quadrosIniciar"]>,
    quadrosParar: () => ipcRenderer.invoke("captura:quadros_parar") as ReturnType<ApiAde["captura"]["quadrosParar"]>,
    listar: (workspaceId, depois) => ipcRenderer.invoke("captura:listar", { workspace_id: workspaceId, depois }) as ReturnType<ApiAde["captura"]["listar"]>,
    ler: (capturaId, workspaceId) => ipcRenderer.invoke("captura:ler", { captura_id: capturaId, workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["ler"]>,
    salvarEdicao: (capturaId, workspaceId, png) => ipcRenderer.invoke("captura:salvar_edicao", { captura_id: capturaId, workspace_id: workspaceId, png }) as ReturnType<ApiAde["captura"]["salvarEdicao"]>,
    anexarAoPane: (capturaId, workspaceId, sessaoId) => ipcRenderer.invoke("captura:anexar_ao_pane", { captura_id: capturaId, workspace_id: workspaceId, sessao_id: sessaoId }) as ReturnType<ApiAde["captura"]["anexarAoPane"]>,
    anexarQuadrosAoPane: (capturaId, workspaceId, sessaoId) => ipcRenderer.invoke("captura:anexar_quadros", { captura_id: capturaId, workspace_id: workspaceId, sessao_id: sessaoId }) as ReturnType<ApiAde["captura"]["anexarQuadrosAoPane"]>,
    copiarCaminho: (capturaId, workspaceId) => ipcRenderer.invoke("captura:copiar_caminho", { captura_id: capturaId, workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["copiarCaminho"]>,
    remover: (capturaId, workspaceId) => ipcRenderer.invoke("captura:remover", { captura_id: capturaId, workspace_id: workspaceId }) as ReturnType<ApiAde["captura"]["remover"]>,
    assinar: (cb) => assinar<CanaisEvento["captura:evento"]>("captura:evento", cb),
  },
  voz: {
    estado: () => ipcRenderer.invoke("voz:estado") as ReturnType<ApiAde["voz"]["estado"]>,
    configGravar: (patch) => ipcRenderer.invoke("voz:config_gravar", { patch }) as ReturnType<ApiAde["voz"]["configGravar"]>,
    segredoGravar: (nome, valor) => ipcRenderer.invoke("voz:segredo_gravar", { nome, valor }) as ReturnType<ApiAde["voz"]["segredoGravar"]>,
    consentir: (servico, host, aceitar) => ipcRenderer.invoke("voz:consentir", { servico, host, aceitar }) as ReturnType<ApiAde["voz"]["consentir"]>,
    testarMotor: () => ipcRenderer.invoke("voz:testar_motor") as ReturnType<ApiAde["voz"]["testarMotor"]>,
    pedirMicrofone: () => ipcRenderer.invoke("voz:pedir_microfone") as ReturnType<ApiAde["voz"]["pedirMicrofone"]>,
    abrirAjustes: (painel) => ipcRenderer.invoke("voz:abrir_ajustes", { painel }) as ReturnType<ApiAde["voz"]["abrirAjustes"]>,
    iniciar: (sessaoId, disparo) => ipcRenderer.invoke("voz:iniciar", { sessao_id: sessaoId, disparo }) as ReturnType<ApiAde["voz"]["iniciar"]>,
    parar: () => ipcRenderer.invoke("voz:parar") as ReturnType<ApiAde["voz"]["parar"]>,
    cancelar: () => ipcRenderer.invoke("voz:cancelar") as ReturnType<ApiAde["voz"]["cancelar"]>,
    audio: (sequencia, dados) => ipcRenderer.send("voz:audio", { sequencia, dados }),
    dicionarioListar: () => ipcRenderer.invoke("voz:dicionario_listar") as ReturnType<ApiAde["voz"]["dicionarioListar"]>,
    dicionarioSalvar: (termo, dica) => ipcRenderer.invoke("voz:dicionario_salvar", { termo, dica }) as ReturnType<ApiAde["voz"]["dicionarioSalvar"]>,
    dicionarioRemover: (termo) => ipcRenderer.invoke("voz:dicionario_remover", { termo }) as ReturnType<ApiAde["voz"]["dicionarioRemover"]>,
    historicoListar: () => ipcRenderer.invoke("voz:historico_listar") as ReturnType<ApiAde["voz"]["historicoListar"]>,
    historicoLimpar: () => ipcRenderer.invoke("voz:historico_limpar") as ReturnType<ApiAde["voz"]["historicoLimpar"]>,
    assinar: (cb) => assinar<CanaisEvento["voz:evento"]>("voz:evento", cb),
    modelosListar: () => ipcRenderer.invoke("voz:modelos_listar") as ReturnType<ApiAde["voz"]["modelosListar"]>,
    modeloBaixar: (pedido) => ipcRenderer.invoke("voz:modelo_baixar", { modelo_id: pedido.modelo_id, aceite_versao: pedido.aceite_versao, ativar: pedido.ativar }) as ReturnType<ApiAde["voz"]["modeloBaixar"]>,
    modeloPausar: (modeloId) => ipcRenderer.invoke("voz:modelo_pausar", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloPausar"]>,
    modeloRetomar: (modeloId) => ipcRenderer.invoke("voz:modelo_retomar", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloRetomar"]>,
    modeloCancelar: (modeloId) => ipcRenderer.invoke("voz:modelo_cancelar", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloCancelar"]>,
    modeloApagar: (modeloId) => ipcRenderer.invoke("voz:modelo_apagar", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloApagar"]>,
    modeloAtivar: (modeloId) => ipcRenderer.invoke("voz:modelo_ativar", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloAtivar"]>,
    modeloAutoteste: (modeloId) => ipcRenderer.invoke("voz:modelo_autoteste", { modelo_id: modeloId }) as ReturnType<ApiAde["voz"]["modeloAutoteste"]>,
    assinarModelos: (cb) => assinar<CanaisEvento["voz:modelo_progresso"]>("voz:modelo_progresso", cb),
  },
  laya: {
    estado: () => ipcRenderer.invoke("laya:estado") as ReturnType<ApiAde["laya"]["estado"]>,
    consentir: (host, aceitar) => ipcRenderer.invoke("laya:consentir", { host, aceitar }) as ReturnType<ApiAde["laya"]["consentir"]>,
    modelosListar: () => ipcRenderer.invoke("laya:modelos_listar") as ReturnType<ApiAde["laya"]["modelosListar"]>,
    modeloBaixar: (pedido) => ipcRenderer.invoke("laya:modelo_baixar", { modelo_id: pedido.modelo_id, aceite_versao: pedido.aceite_versao, ativar: pedido.ativar }) as ReturnType<ApiAde["laya"]["modeloBaixar"]>,
    modeloPausar: (modeloId) => ipcRenderer.invoke("laya:modelo_pausar", { modelo_id: modeloId }) as ReturnType<ApiAde["laya"]["modeloPausar"]>,
    modeloRetomar: (modeloId) => ipcRenderer.invoke("laya:modelo_retomar", { modelo_id: modeloId }) as ReturnType<ApiAde["laya"]["modeloRetomar"]>,
    modeloCancelar: (modeloId) => ipcRenderer.invoke("laya:modelo_cancelar", { modelo_id: modeloId }) as ReturnType<ApiAde["laya"]["modeloCancelar"]>,
    modeloApagar: (modeloId) => ipcRenderer.invoke("laya:modelo_apagar", { modelo_id: modeloId }) as ReturnType<ApiAde["laya"]["modeloApagar"]>,
    modeloAtivar: (modeloId) => ipcRenderer.invoke("laya:modelo_ativar", { modelo_id: modeloId }) as ReturnType<ApiAde["laya"]["modeloAtivar"]>,
    testar: () => ipcRenderer.invoke("laya:testar") as ReturnType<ApiAde["laya"]["testar"]>,
    configGravar: (patch) => ipcRenderer.invoke("laya:config_gravar", { patch }) as ReturnType<ApiAde["laya"]["configGravar"]>,
    assinarModelos: (cb) => assinar<CanaisEvento["laya:modelo_progresso"]>("laya:modelo_progresso", cb),
    assinarEstado: (cb) => assinar<CanaisEvento["laya:estado_mudou"]>("laya:estado_mudou", cb),
  },
  bench: {
    tarefasListar: (atividade, estado) => ipcRenderer.invoke("bench:tarefas_listar", { atividade, estado }) as ReturnType<ApiAde["bench"]["tarefasListar"]>,
    tarefaSalvar: (tarefa) => ipcRenderer.invoke("bench:tarefa_salvar", { tarefa }) as ReturnType<ApiAde["bench"]["tarefaSalvar"]>,
    alvosListar: () => ipcRenderer.invoke("bench:alvos_listar") as ReturnType<ApiAde["bench"]["alvosListar"]>,
    alvosSalvar: (alvos) => ipcRenderer.invoke("bench:alvos_salvar", { alvos }) as ReturnType<ApiAde["bench"]["alvosSalvar"]>,
    precosLer: () => ipcRenderer.invoke("bench:precos_ler") as ReturnType<ApiAde["bench"]["precosLer"]>,
    precosGravar: (precos) => ipcRenderer.invoke("bench:precos_gravar", { precos }) as ReturnType<ApiAde["bench"]["precosGravar"]>,
    estimar: (p) => ipcRenderer.invoke("bench:estimar", p) as ReturnType<ApiAde["bench"]["estimar"]>,
    consentir: (estimativaId, confirmacao, finalidade) => ipcRenderer.invoke("bench:consentir", { estimativa_id: estimativaId, confirmacao, ...(finalidade === undefined ? {} : { finalidade }) }) as ReturnType<ApiAde["bench"]["consentir"]>,
    descartarConsentimento: (estimativaId) => ipcRenderer.invoke("bench:descartar_consentimento", { estimativa_id: estimativaId }) as ReturnType<ApiAde["bench"]["descartarConsentimento"]>,
    rodar: (estimativaId, token) => ipcRenderer.invoke("bench:rodar", { estimativa_id: estimativaId, token }) as ReturnType<ApiAde["bench"]["rodar"]>,
    cancelar: (runId) => ipcRenderer.invoke("bench:cancelar", { run_id: runId }) as ReturnType<ApiAde["bench"]["cancelar"]>,
    rerodar: (runId, tarefa, alvo, token) => ipcRenderer.invoke("bench:rerodar", { run_id: runId, tarefa, alvo, token }) as ReturnType<ApiAde["bench"]["rerodar"]>,
    julgar: (runId, tarefa, juizAlvo, token) => ipcRenderer.invoke("bench:julgar", { run_id: runId, tarefa, juiz_alvo: juizAlvo, token }) as ReturnType<ApiAde["bench"]["julgar"]>,
    notaManual: (resultadoId, nota, notas) => ipcRenderer.invoke("bench:nota_manual", { resultado_id: resultadoId, nota, notas }) as ReturnType<ApiAde["bench"]["notaManual"]>,
    runsListar: (depois) => ipcRenderer.invoke("bench:runs_listar", { depois }) as ReturnType<ApiAde["bench"]["runsListar"]>,
    estadoRun: (runId) => ipcRenderer.invoke("bench:estado_run", { run_id: runId }) as ReturnType<ApiAde["bench"]["estadoRun"]>,
    resultado: (resultadoId) => ipcRenderer.invoke("bench:resultado", { resultado_id: resultadoId }) as ReturnType<ApiAde["bench"]["resultado"]>,
    logLer: (resultadoId, depois, max) => ipcRenderer.invoke("bench:log_ler", { resultado_id: resultadoId, depois, max }) as ReturnType<ApiAde["bench"]["logLer"]>,
    artefatoLer: (resultadoId, nome) => ipcRenderer.invoke("bench:artefato_ler", { resultado_id: resultadoId, nome }) as ReturnType<ApiAde["bench"]["artefatoLer"]>,
    comparar: (alvos, tarefas, agrupar) => ipcRenderer.invoke("bench:comparar", { alvos, tarefas, agrupar }) as ReturnType<ApiAde["bench"]["comparar"]>,
    recomendar: (atividade, restricoes, estrategia) => ipcRenderer.invoke("bench:recomendar", { atividade, restricoes, estrategia }) as ReturnType<ApiAde["bench"]["recomendar"]>,
    exportarPolitica: (atividades) => ipcRenderer.invoke("bench:exportar_politica", { atividades }) as ReturnType<ApiAde["bench"]["exportarPolitica"]>,
    exportarRelatorio: (runIds, formato) => ipcRenderer.invoke("bench:exportar_relatorio", { run_ids: runIds, formato }) as ReturnType<ApiAde["bench"]["exportarRelatorio"]>,
    assinar: (cb) => assinar<CanaisEvento["bench:evento"]>("bench:evento", cb),
  },
  jarvis: {
    estado: () => ipcRenderer.invoke("jarvis:estado") as ReturnType<ApiAde["jarvis"]["estado"]>,
    configGravar: (patch) => ipcRenderer.invoke("jarvis:config_gravar", { patch }) as ReturnType<ApiAde["jarvis"]["configGravar"]>,
    enviar: (texto) => ipcRenderer.invoke("jarvis:enviar", { texto }) as ReturnType<ApiAde["jarvis"]["enviar"]>,
    acao: (acao) => ipcRenderer.invoke("jarvis:acao", { acao }) as ReturnType<ApiAde["jarvis"]["acao"]>,
    confirmar: (confirmacaoId, aprovado) => ipcRenderer.invoke("jarvis:confirmar", { confirmacao_id: confirmacaoId, aprovado }) as ReturnType<ApiAde["jarvis"]["confirmar"]>,
    historico: (depois) => ipcRenderer.invoke("jarvis:historico", { depois }) as ReturnType<ApiAde["jarvis"]["historico"]>,
    limparConversa: () => ipcRenderer.invoke("jarvis:limpar") as ReturnType<ApiAde["jarvis"]["limparConversa"]>,
    assinar: (cb) => assinar<CanaisEvento["jarvis:evento"]>("jarvis:evento", cb),
    assinarNavegacao: (cb) => assinar<CanaisEvento["jarvis:abrir_pane"]>("jarvis:abrir_pane", cb),
  },
  remoto: {
    estado: () => ipcRenderer.invoke("remoto:estado") as ReturnType<ApiAde["remoto"]["estado"]>,
    ligar: (pedido) => ipcRenderer.invoke("remoto:ligar", pedido) as ReturnType<ApiAde["remoto"]["ligar"]>,
    desligar: () => ipcRenderer.invoke("remoto:desligar") as ReturnType<ApiAde["remoto"]["desligar"]>,
    configGravar: (patch) => ipcRenderer.invoke("remoto:config_gravar", { patch }) as ReturnType<ApiAde["remoto"]["configGravar"]>,
    parearIniciar: (permissao) => ipcRenderer.invoke("remoto:parear_iniciar", { permissao }) as ReturnType<ApiAde["remoto"]["parearIniciar"]>,
    parearCancelar: () => ipcRenderer.invoke("remoto:parear_cancelar") as ReturnType<ApiAde["remoto"]["parearCancelar"]>,
    parearConfirmarSas: (pedido) => ipcRenderer.invoke("remoto:parear_confirmar_sas", pedido) as ReturnType<ApiAde["remoto"]["parearConfirmarSas"]>,
    revogar: (dispositivoId) => ipcRenderer.invoke("remoto:revogar", { dispositivo_id: dispositivoId }) as ReturnType<ApiAde["remoto"]["revogar"]>,
    permissaoDefinir: (pedido) => ipcRenderer.invoke("remoto:permissao_definir", pedido) as ReturnType<ApiAde["remoto"]["permissaoDefinir"]>,
    aprovarPedido: (pedidoId, aprovado) => ipcRenderer.invoke("remoto:aprovar_pedido", { pedido_id: pedidoId, aprovado }) as ReturnType<ApiAde["remoto"]["aprovarPedido"]>,
    panico: () => ipcRenderer.invoke("remoto:panico") as ReturnType<ApiAde["remoto"]["panico"]>,
    auditoria: (depois) => ipcRenderer.invoke("remoto:auditoria", { depois }) as ReturnType<ApiAde["remoto"]["auditoria"]>,
    assinar: (cb) => assinar<CanaisEvento["remoto:evento"]>("remoto:evento", cb),
  },
  relay: {
    estado: () => ipcRenderer.invoke("relay:estado") as ReturnType<ApiAde["relay"]["estado"]>,
    configObter: () => ipcRenderer.invoke("relay:config_obter") as ReturnType<ApiAde["relay"]["configObter"]>,
    configDefinir: (patch) => ipcRenderer.invoke("relay:config_definir", patch) as ReturnType<ApiAde["relay"]["configDefinir"]>,
    ligar: () => ipcRenderer.invoke("relay:ligar") as ReturnType<ApiAde["relay"]["ligar"]>,
    desligar: () => ipcRenderer.invoke("relay:desligar") as ReturnType<ApiAde["relay"]["desligar"]>,
    parearIniciar: () => ipcRenderer.invoke("relay:parear_iniciar", { permissao_inicial: "leitura" }) as ReturnType<ApiAde["relay"]["parearIniciar"]>,
    parearSas: () => ipcRenderer.invoke("relay:parear_sas") as ReturnType<ApiAde["relay"]["parearSas"]>,
    parearDecidir: (permitir) => ipcRenderer.invoke("relay:parear_decidir", { permitir }) as ReturnType<ApiAde["relay"]["parearDecidir"]>,
    dispositivos: () => ipcRenderer.invoke("relay:dispositivos") as ReturnType<ApiAde["relay"]["dispositivos"]>,
    revogar: (dispositivoId) => ipcRenderer.invoke("relay:revogar", { dispositivo_id: dispositivoId }) as ReturnType<ApiAde["relay"]["revogar"]>,
    panico: () => ipcRenderer.invoke("relay:panico") as ReturnType<ApiAde["relay"]["panico"]>,
    assinar: (cb) => assinar<CanaisEvento["relay:evento"]>("relay:evento", cb),
  },
  suite: {
    estado: (workspaceId) => ipcRenderer.invoke("suite:estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["suite"]["estado"]>,
    requisitos: (workspaceId) => ipcRenderer.invoke("suite:requisitos", { workspace_id: workspaceId }) as ReturnType<ApiAde["suite"]["requisitos"]>,
    instalar: (workspaceId, modo) => ipcRenderer.invoke("suite:instalar", { workspace_id: workspaceId, modo }) as ReturnType<ApiAde["suite"]["instalar"]>,
    cancelar: (workspaceId) => ipcRenderer.invoke("suite:cancelar", { workspace_id: workspaceId }) as ReturnType<ApiAde["suite"]["cancelar"]>,
    dispensar: (workspaceId, dispensar) => ipcRenderer.invoke("suite:dispensar", { workspace_id: workspaceId, dispensar }) as ReturnType<ApiAde["suite"]["dispensar"]>,
    assinar: (cb) => assinar<CanaisEvento["suite:progresso"]>("suite:progresso", cb),
    modulosEstado: (workspaceId) => ipcRenderer.invoke("suite:modulos_estado", { workspace_id: workspaceId }) as ReturnType<ApiAde["suite"]["modulosEstado"]>,
    modulosDefinir: (workspaceId, modulo, ligado, confirmarCascata) => ipcRenderer.invoke("suite:modulos_definir", { workspace_id: workspaceId, modulo, ligado, confirmar_cascata: confirmarCascata }) as ReturnType<ApiAde["suite"]["modulosDefinir"]>,
    modulosRestaurar: (workspaceId) => ipcRenderer.invoke("suite:modulos_restaurar", { workspace_id: workspaceId }) as ReturnType<ApiAde["suite"]["modulosRestaurar"]>,
    modulosPadrao: () => ipcRenderer.invoke("suite:modulos_padrao", {}) as ReturnType<ApiAde["suite"]["modulosPadrao"]>,
    modulosPadraoDefinir: (modulos) => ipcRenderer.invoke("suite:modulos_padrao_definir", { modulos }) as ReturnType<ApiAde["suite"]["modulosPadraoDefinir"]>,
    assinarModulos: (cb) => assinar<CanaisEvento["suite:modulos_mudou"]>("suite:modulos_mudou", cb),
  },
  bichinho: {
    listar: (workspaceIds) => ipcRenderer.invoke("bichinho:listar", { workspace_ids: [...workspaceIds] }) as ReturnType<ApiAde["bichinho"]["listar"]>,
    obter: (workspaceId) => ipcRenderer.invoke("bichinho:obter", { workspace_id: workspaceId }) as ReturnType<ApiAde["bichinho"]["obter"]>,
    trocarEspecie: (workspaceId, especie) => ipcRenderer.invoke("bichinho:trocar_especie", { workspace_id: workspaceId, especie }) as ReturnType<ApiAde["bichinho"]["trocarEspecie"]>,
    renomear: (workspaceId, apelido) => ipcRenderer.invoke("bichinho:renomear", { workspace_id: workspaceId, apelido }) as ReturnType<ApiAde["bichinho"]["renomear"]>,
    atencao: (workspaceId) => ipcRenderer.invoke("bichinho:atencao", { workspace_id: workspaceId }) as ReturnType<ApiAde["bichinho"]["atencao"]>,
    usos: () => ipcRenderer.invoke("bichinho:usos") as ReturnType<ApiAde["bichinho"]["usos"]>,
    assinar: (cb) => assinar<CanaisEvento["bichinho:mudou"]>("bichinho:mudou", cb),
  },
  sistema: {
    assinar: (ativo) => ipcRenderer.invoke("sistema:amostra_assinar", { ativo }) as ReturnType<ApiAde["sistema"]["assinar"]>,
    detalhe: (aberto) => ipcRenderer.invoke("sistema:detalhe", { aberto }) as ReturnType<ApiAde["sistema"]["detalhe"]>,
    aoAmostra: (cb) => assinar<CanaisEvento["sistema:amostra"]>("sistema:amostra", cb),
  },
  progresso: {
    estado: () => ipcRenderer.invoke("progresso:estado") as ReturnType<ApiAde["progresso"]["estado"]>,
    dispensar: (id) => ipcRenderer.invoke("progresso:dispensar", { id }) as ReturnType<ApiAde["progresso"]["dispensar"]>,
    fixar: (id, fixado) => ipcRenderer.invoke("progresso:fixar", { id, fixado }) as ReturnType<ApiAde["progresso"]["fixar"]>,
    assinar: (cb) => assinar<CanaisEvento["progresso:mudou"]>("progresso:mudou", cb),
  },
};

contextBridge.exposeInMainWorld("ade", api);
