// Fase 16 · Maestro (núcleo puro). Só reexporta: nada roda no boot; o main liga as portas quando o usuário pede (leveza).
export * from "./etapas/catalogo";
export * from "./etapas/conclusao";
export { classificarIntencao, LIMITE_ALTA, LIMITE_MEDIA, type ContextoClassificacao } from "./intencao/classificar";
export { combinarRegraEDecisor, deveConsultarDecisor, type CasoCombinacao, type ResultadoCombinacao } from "./intencao/combinar";
export { LEXICO, type EntradaLexico } from "./intencao/lexico";
export { normalizar } from "./intencao/normalizar";
export * from "./decisor/cliente";
export { OPCOES_DO_DECISOR, PROMPT_DECISOR_INTENCAO, VERSAO_PROMPT_DECISOR } from "./decisor/prompt";
export * from "./recibo";
export * from "./perfis/padroes";
export * from "./perfis/portabilidade";
export * from "./perfis/resolver";
export * from "./perfis/validar";
export * from "./rigidez/niveis";
export * from "./rigidez/matriz";
export * from "./rigidez/plano-de-etapas";
export * from "./rigidez/instrucoes";
export * from "./rigidez/piso";
export * from "./rigidez/travas";
export * from "./rigidez/escopos";
export * from "./rigidez/hooks";
export * from "./planejar";
export * from "./config";
export * from "./guardas";
export * from "./maquina";
export * from "./despachante";
export * from "./servico";
export * from "./openrouter/uso";
export { criarPortaMaestroMcp, erroMcpDoMaestro, MENSAGEM_DO_MAESTRO, type DepsPortaMaestroMcp, type ServicoParaMcp } from "./mcp";
