// As 86 receitas das espécies novas (D-674). Cada uma: arquétipo (a), paleta (p), partes (o orelha, c cauda, f focinho/bico, x extras, m marca) e traços (t).
// A arte das 14 espécies originais NÃO está aqui: continua em `arte.tsx` (legada, preservada pixel a pixel).
import type { EspecieId } from "../../../compartilhado/bichinho";
import type { Receita } from "./tipos";

export type EspecieNova = Exclude<EspecieId, "caranguejo" | "piton" | "esquilo" | "raposa" | "camaleao" | "lontra" | "tucano" | "elefante" | "ourico" | "coruja" | "polvo" | "gato" | "sapo" | "urso">;

export const RECEITAS: Readonly<Record<EspecieNova, Receita>> = {
  // ---- mamíferos
  capivara: { a: "roedor", p: 1, o: "pequena", c: "nenhuma", f: "largo", v: "gordo", t: ["calma", "sociável"] },
  lobo: { a: "canino", p: 2, t: ["líder", "leal"] },
  tigre: { a: "felino", p: 12, o: "redonda", m: "listras", t: ["preciso", "silencioso"] },
  leao: { a: "felino", p: 0, o: "redonda", x: ["juba"], t: ["majestoso", "calmo"] },
  pantera: { a: "felino", p: 16, t: ["discreta", "vigilante"] },
  lince: { a: "felino", p: 9, o: "tufo", c: "curta", t: ["afiado", "atento"] },
  guepardo: { a: "felino", p: 15, o: "redonda", m: "pintas", v: "fino", t: ["veloz", "econômico"] },
  onca: { a: "felino", p: 0, o: "redonda", m: "pintas", v: "gordo", t: ["forte", "silenciosa"] },
  panda: { a: "ursino", p: 3, m: "olheiras", t: ["terno", "calmo"] },
  coala: { a: "ursino", p: 2, o: "grande", f: "nariz", c: "nenhuma", t: ["sonolento", "carinhoso"] },
  canguru: { a: "canino", p: 1, o: "longa", c: "longa", x: ["bolsa"], t: ["saltador", "prático"] },
  preguica: { a: "ursino", p: 9, o: "nenhuma", m: "mascara", c: "nenhuma", v: "gordo", t: ["devagar", "constante"] },
  tamandua: { a: "canino", p: 2, o: "pequena", f: "longo", c: "tufo", t: ["curioso", "paciente"] },
  tatu: { a: "roedor", p: 1, o: "pequena", x: ["bandas"], c: "fina", t: ["blindado", "teimoso"] },
  anta: { a: "ungulado", p: 16, f: "tromba", o: "redonda", c: "curta", v: "gordo", t: ["antiga", "resistente"] },
  suricato: { a: "roedor", p: 9, o: "pequena", m: "olheiras", t: ["sentinela", "alerta"] },
  lemure: { a: "primata", p: 2, m: "olheiras", c: "listrada", t: ["ágil", "brincalhão"] },
  macaco: { a: "primata", p: 1, c: "enrolada", t: ["curioso", "ágil"] },
  gorila: { a: "primata", p: 16, x: ["topete"], v: "gordo", c: "nenhuma", t: ["forte", "tranquilo"] },
  cervo: { a: "ungulado", p: 1, x: ["galhada"], m: "pintas", c: "curta", t: ["gracioso", "atento"] },
  alce: { a: "ungulado", p: 1, x: ["galhadaL"], f: "largo", c: "curta", t: ["amplo", "tranquilo"] },
  camelo: { a: "ungulado", p: 9, o: "pequena", x: ["corcova"], c: "fina", t: ["resistente", "paciente"] },
  lhama: { a: "ungulado", p: 3, o: "banana", x: ["pescoco", "topete"], c: "curta", t: ["calma", "elegante"] },
  cavalo: { a: "ungulado", p: 1, x: ["crista"], c: "tufo", t: ["trabalhador", "leal"] },
  zebra: { a: "ungulado", p: 3, m: "listras", x: ["crista"], t: ["preto no branco", "exata"] },
  girafa: { a: "ungulado", p: 0, m: "pintasG", x: ["ossicones", "pescoco"], c: "fina", t: ["alta", "ampla"] },
  rinoceronte: { a: "ungulado", p: 2, o: "redonda", x: ["chifre"], v: "gordo", c: "fina", t: ["blindado", "teimoso"] },
  hipopotamo: { a: "ungulado", p: 13, f: "largo", o: "pequena", v: "gordo", c: "curta", t: ["grande", "tranquilo"] },
  javali: { a: "ungulado", p: 1, f: "porco", x: ["presasJ"], c: "curta", t: ["bruto", "decidido"] },
  "porco-espinho": { a: "roedor", p: 1, o: "pequena", x: ["espinhos"], c: "nenhuma", t: ["defensivo", "reservado"] },
  castor: { a: "roedor", p: 1, c: "chata", t: ["construtor", "incansável"] },
  ornitorrinco: { a: "roedor", p: 1, o: "nenhuma", f: "chato", c: "chata", t: ["híbrido", "singular"] },
  vombate: { a: "ursino", p: 1, o: "pequena", f: "nariz", c: "nenhuma", v: "gordo", t: ["cavador", "teimoso"] },
  quokka: { a: "roedor", p: 9, o: "redonda", c: "curta", t: ["sorridente", "otimista"] },
  morcego: { a: "roedor", p: 16, o: "morcego", x: ["asasM"], c: "nenhuma", t: ["noturno", "sensível"] },
  coelho: { a: "roedor", p: 3, o: "longa", c: "curta", t: ["rápido", "saltitante"] },
  ovelha: { a: "ungulado", p: 3, hs: 1, o: "caida", x: ["la"], c: "curta", t: ["gregária", "mansa"] },
  guaxinim: { a: "ursino", p: 2, m: "mascara", c: "listrada", t: ["fuçador", "esperto"] },
  texugo: { a: "ursino", p: 16, o: "pequena", x: ["faixa"], c: "curta", t: ["teimoso", "resiliente"] },
  bisao: { a: "ungulado", p: 1, x: ["juba", "chifres"], f: "largo", v: "gordo", c: "curta", t: ["imponente", "lento"] },
  foca: { a: "ursino", p: 2, o: "nenhuma", x: ["aletas", "bigodes"], c: "nenhuma", t: ["equilibrista", "brincalhona"] },
  // ---- aves
  arara: { a: "ave", p: 5, f: "grosso", bc: "c", x: ["asas"], t: ["colorida", "falante"] },
  pinguim: { a: "aquatica", p: 16, bl: 1, x: ["aletas"], c: "nenhuma", t: ["elegante", "frio"] },
  falcao: { a: "ave", p: 1, f: "curvo", x: ["asas"], t: ["afiado", "veloz"] },
  corvo: { a: "ave", p: 16, f: "reto", bc: "e", x: ["asas"], t: ["esperto", "colecionador"] },
  pavao: { a: "ave", p: 7, c: "leque", x: ["crista"], t: ["vistoso", "vaidoso"] },
  flamingo: { a: "aquatica", p: 8, f: "flamingo", x: ["pescoco", "asas"], t: ["equilibrado", "gracioso"] },
  pato: { a: "aquatica", p: 15, x: ["asas"], t: ["adaptável", "divertido"] },
  cisne: { a: "aquatica", p: 3, x: ["pescoco", "asas"], t: ["sereno", "elegante"] },
  pelicano: { a: "aquatica", p: 3, f: "pelicano", x: ["asas"], t: ["previdente", "paciente"] },
  "beija-flor": { a: "ave", p: 4, f: "fino", x: ["asasI"], v: "fino", t: ["veloz", "minúsculo"] },
  avestruz: { a: "ave", p: 2, x: ["pescoco"], t: ["corredor", "ressabiado"] },
  gaivota: { a: "aquatica", p: 3, f: "curvo", x: ["asas"], t: ["livre", "faminta"] },
  // ---- répteis
  tartaruga: { a: "reptil", p: 4, x: ["casco"], c: "curta", v: "gordo", t: ["segura", "paciente"] },
  jacare: { a: "reptil", p: 10, f: "croc", x: ["dentes"], t: ["emboscado", "paciente"] },
  lagarto: { a: "reptil", p: 14, m: "pintas", v: "fino", t: ["leve", "rápido"] },
  iguana: { a: "reptil", p: 4, x: ["crista", "papada"], t: ["calma", "alinhada"] },
  komodo: { a: "reptil", p: 1, x: ["lingua"], v: "gordo", t: ["pesado", "paciente"] },
  osga: { a: "reptil", p: 9, m: "pintas", x: ["ventosas"], v: "fino", t: ["pequena", "grudada"] },
  // ---- anfíbios
  axolote: { a: "salamandra", p: 8, x: ["gills"], c: "chata", t: ["sorridente", "regenerativo"] },
  salamandra: { a: "salamandra", p: 16, m: "pintas", t: ["resistente", "serena"] },
  perereca: { a: "anfibio", p: 14, x: ["ventosas"], t: ["grudenta", "ágil"] },
  // ---- peixes e cetáceos
  baleia: { a: "peixe", p: 11, x: ["jato"], v: "gordo", bl: 1, t: ["imensa", "cantora"] },
  golfinho: { a: "peixe", p: 18, f: "bicoD", bl: 1, t: ["esperto", "brincalhão"] },
  tubarao: { a: "peixe", p: 2, x: ["dorsal", "dentes"], bl: 1, t: ["farejador", "frio"] },
  arraia: { a: "peixe", p: 7, x: ["raia"], t: ["fluida", "silenciosa"] },
  baiacu: { a: "peixe", p: 15, x: ["raios"], v: "gordo", t: ["defensivo", "redondo"] },
  "cavalo-marinho": { a: "peixe", p: 0, f: "tubo", c: "enrolada", x: ["aneis", "crista"], v: "fino", t: ["enrolado", "raro"] },
  "peixe-lua": { a: "peixe", p: 2, x: ["mola"], v: "gordo", t: ["calmo", "enorme"] },
  // ---- invertebrados
  "agua-viva": { a: "medusa", p: 7, v: "agua", t: ["leve", "brilhante"] },
  "estrela-do-mar": { a: "estrela", p: 0, t: ["regenerativa", "calma"] },
  lula: { a: "medusa", p: 8, v: "lula", t: ["veloz", "enigmática"] },
  lagosta: { a: "crustaceo", p: 12, t: ["blindada", "firme"] },
  nautilo: { a: "caracol", p: 9, v: "nautilo", m: "listras", t: ["espiral", "antigo"] },
  caracol: { a: "caracol", p: 10, t: ["lento", "autossuficiente"] },
  // ---- insetos e aracnídeos
  abelha: { a: "inseto", p: 15, m: "listras", x: ["asasI", "antenas"], t: ["trabalhadora", "organizada"] },
  joaninha: { a: "inseto", p: 17, hs: 1, m: "pintas", x: ["domo", "antenas"], t: ["caçadora", "sortuda"] },
  borboleta: { a: "inseto", p: 6, x: ["asasB", "antenas"], v: "fino", t: ["leve", "transformadora"] },
  "louva-a-deus": { a: "inseto", p: 4, x: ["foices", "antenas"], v: "fino", t: ["imóvel", "preciso"] },
  escaravelho: { a: "inseto", p: 11, x: ["domo", "chifre"], t: ["persistente", "forte"] },
  formiga: { a: "inseto", p: 12, v: "ant", x: ["antenas"], t: ["coletiva", "incansável"] },
  libelula: { a: "inseto", p: 7, x: ["asasL"], v: "fino", t: ["ágil", "leve"] },
  grilo: { a: "inseto", p: 10, x: ["antenasL", "pernaSalto"], t: ["cantor", "consciente"] },
  "vaga-lume": { a: "inseto", p: 16, x: ["luz", "asasI", "antenas"], t: ["luminoso", "noturno"] },
  aranha: { a: "aracnideo", p: 16, t: ["tecelã", "sensível"] },
  escorpiao: { a: "aracnideo", p: 12, x: ["pincas", "caudaE"], t: ["armado", "reservado"] },
};
