// Lista de mutações da Fase 13 (Jarvis e controle remoto): cada item remove UMA mitigação de segurança (troca de um trecho exato do fonte) e aponta o(s) teste(s) que PRECISAM
// falhar. Rodar: `node tests/scripts/mutacao-fase13.mjs [AR-05 ...]`. A consistência (trecho aparece 1 vez, teste existe) é conferida por `mutacao-fase13.test.ts`.
const ADV = "src/nucleo/remoto/adversarial.test.ts";
const REM = "src/nucleo/remoto/servico.test.ts";
const PRO = "src/nucleo/remoto/protocolo.test.ts";
const JAR = "src/nucleo/jarvis/servico.test.ts";
const CNF = "src/nucleo/jarvis/confirmacao.test.ts";
const NET = "src/nucleo/remoto/servidor.test.ts";

export const MUTACOES = [
  { id: "AR-05a", descricao: "confirmação aceita voz/remoto como resolvedor", arquivo: "src/nucleo/jarvis/confirmacao.ts", de: 'const RESOLVEDORES: readonly string[] = ["ui", "desktop"];', para: 'const RESOLVEDORES: readonly string[] = ["ui", "desktop", "voz", "remoto", "conteudo_externo"];', testes: [ADV], nome: "ar05_confirmacao_uso_unico" },
  { id: "AR-05b", descricao: "confirmação deixa de ser de uso único", arquivo: "src/nucleo/jarvis/confirmacao.ts", de: "      mapa.delete(id); // uso único: queima ANTES de qualquer outra coisa", para: "      // (mutado) não queima", testes: [ADV], nome: "ar05_confirmacao_uso_unico" },
  { id: "AR-06a", descricao: "confirmação não confere o args_hash do payload congelado", arquivo: "src/nucleo/jarvis/confirmacao.ts", de: 'if (hashArgs({ acao: c.acao, resumo: c.resumo, payload: c.payload }) !== c.args_hash) return { ok: false, codigo: "confirmacao_invalida", confirmacao: c };', para: "", testes: [CNF], nome: "hash adulterado" },
  { id: "AR-06b", descricao: "execução não confere o hash do plano VIVO (TOCTOU)", arquivo: "src/nucleo/jarvis/servico.ts", de: 'atual.args_hash !== payload["plano_hash"]', para: "false", testes: [ADV, JAR], nome: "ar06_args_hash_e_plano_vivo|TOCTOU" },
  { id: "AR-01a", descricao: "matriz deixa conteúdo externo escrever", arquivo: "src/nucleo/jarvis/acoes.ts", de: 'if (p.origem === "conteudo_externo" && risco !== "leitura")', para: 'if (false && risco !== "leitura")', testes: [ADV], nome: "ar01_conteudo_externo_nao_vira_comando" },
  { id: "AR-01b", descricao: "texto de conteúdo externo passa a ser interpretado", arquivo: "src/nucleo/jarvis/servico.ts", de: 'if (e.origem === "conteudo_externo") {', para: "if (false) {", testes: [ADV], nome: "ar01_conteudo_externo_nao_vira_comando" },
  { id: "AR-04a", descricao: "gesto proibido (merge, apagar, assinar) deixa de ser barrado no texto", arquivo: "src/nucleo/jarvis/classificador.ts", de: 'const gesto = gestoProibidoNoTexto(t);\n  if (gesto !== null) return { tipo: "recusado", gesto };', para: "", testes: [ADV], nome: "ar04_gestos_humanos_nunca" },
  { id: "AR-04b", descricao: "portão que exige humano deixa de ser barrado (proposta E execução)", edicoes: [
    { arquivo: "src/nucleo/jarvis/servico.ts", de: 'if (alvo.exige_humano) return { tipo: "recusa", codigo: "acao_humana_so_no_desktop" };', para: "" },
    { arquivo: "src/nucleo/jarvis/servico.ts", de: 'if (alvo.exige_humano) return recusa("acao_humana_so_no_desktop", TEXTO_RECUSA.acao_humana_so_no_desktop);', para: "" },
  ], testes: [ADV, JAR], nome: "ar04_gestos_humanos_nunca|exige humano" },
  { id: "AR-14", descricao: "dispositivo `leitura` passa a poder escrever", arquivo: "src/nucleo/jarvis/acoes.ts", de: 'if (p.permissao === "leitura") return { permitido: false, confirmacao: "desktop", codigo: "permissao_insuficiente" };', para: "", testes: [ADV], nome: "ar14_leitura_nao_escreve" },
  { id: "AR-07a", descricao: "janela de pareamento não fecha após 5 erros", arquivo: "src/nucleo/remoto/protocolo.ts", de: 'if (erradas >= maxErradas) fechar("tentativas");', para: 'if (false) fechar("tentativas");', testes: [ADV, PRO], nome: "ar07_forca_bruta_pareamento|5x fecha" },
  { id: "AR-07b", descricao: "MAC do pareamento aceita qualquer confirmação", arquivo: "src/nucleo/remoto/protocolo.ts", de: "const igual = (a: Buffer, b: Buffer): boolean => a.length === b.length && timingSafeEqual(a, b);", para: "const igual = (a: Buffer, b: Buffer): boolean => (void a, void b, true);", testes: [ADV, PRO], nome: "ar07_forca_bruta_pareamento|atacante sem o código" },
  { id: "AR-09a", descricao: "Host deixa de ser conferido (política)", arquivo: "src/nucleo/remoto/politica-rede.ts", de: "return aceitos.has(h);", para: "return true;", testes: [ADV], nome: "ar09_dns_rebinding_host" },
  { id: "AR-09b", descricao: "Host deixa de ser conferido (servidor)", arquivo: "src/nucleo/remoto/servidor.ts", de: "if (!hostPermitido(req.headers.host, opHost)) {", para: "if (false) {", testes: [ADV], nome: "ar09_dns_rebinding_host" },
  { id: "AR-10a", descricao: "Origin de terceiro deixa de ser recusado (política)", arquivo: "src/nucleo/remoto/politica-rede.ts", de: "return hostPermitido(u.host, o);", para: "return true;", testes: [ADV], nome: "ar10_csrf_origin_e_content_type" },
  { id: "AR-10b", descricao: "Origin de terceiro deixa de ser recusado (servidor)", arquivo: "src/nucleo/remoto/servidor.ts", de: "if (!origemDoNavegadorPermitida(Array.isArray(origin) ? origin[0] : origin, opHost)) {", para: "if (false) {", testes: [ADV], nome: "ar10_csrf_origin_e_content_type" },
  { id: "AR-10c", descricao: "Content-Type não é exigido (POST simples de formulário)", arquivo: "src/nucleo/remoto/servidor.ts", de: 'if (!/^application\\/json(?:\\s*;.*)?$/i.test(req.headers["content-type"] ?? "")) {', para: "if (false) {", testes: [ADV], nome: "ar10_csrf_origin_e_content_type" },
  { id: "AR-11", descricao: "canal aceita contador repetido/menor (replay)", arquivo: "src/nucleo/remoto/protocolo.ts", de: "n <= ultimo ||", para: "n < 0 ||", testes: [ADV, PRO], nome: "ar11_replay_quadros|canal: quadro repetido" },
  { id: "AR-13", descricao: "IP público passa a ser aceito", arquivo: "src/nucleo/remoto/politica-rede.ts", de: 'return transporte === "loopback" ? ehLoopback(ipRemoto) : ipPrivado(ipRemoto, op);', para: "return true;", testes: [ADV], nome: "ar13_ip_publico_recusado" },
  { id: "AR-27", descricao: "bind aceita qualquer IP (curinga)", edicoes: [
    { arquivo: "src/nucleo/remoto/politica-rede.ts", de: 'if (n === "0.0.0.0" || n === "::" || n === "::0") return false;', para: "" },
    { arquivo: "src/nucleo/remoto/politica-rede.ts", de: 'return transporte === "loopback" ? ehLoopback(n) : ipPrivado(n, op);', para: "return true;" },
  ], testes: [ADV], nome: "ar27_bind_nunca_curinga" },
  { id: "AR-17a", descricao: "dispositivo revogado/expirado autentica", arquivo: "src/nucleo/remoto/dispositivos.ts", de: "if (x === undefined || x.revogado_em !== null || Date.parse(x.expira_em) <= d.relogio.agora()) return null;", para: "if (x === undefined) return null;", testes: [ADV, REM], nome: "ar17_revogado_nunca_autentica|revogar derruba|expirado/revogado" },
  { id: "AR-17b", descricao: "sessão aberta não reconfere o dispositivo a cada requisição", arquivo: "src/nucleo/remoto/servico.ts", de: "const disp = d.dispositivos.ativo(s.dispositivo_id);", para: "const disp = d.dispositivos.listar().find((x) => x.id === s.dispositivo_id) ?? null;", testes: [REM], nome: "expirado/revogado" },
  { id: "AR-17c", descricao: "pedido de sessão sem verificar a assinatura do dispositivo", arquivo: "src/nucleo/remoto/protocolo.ts", de: "if (!verificarAssinatura(chave, dadosAssinadosCliente(dispositivoId, epk, nonceC, ts), sig)) return null;", para: "", testes: [PRO, REM], nome: "replay do pedido|assinatura de outra chave" },
  { id: "AR-17d", descricao: "pedido de sessão sem anti-replay do nonce", arquivo: "src/nucleo/remoto/protocolo.ts", de: "if (deps.jaVisto !== undefined ? deps.jaVisto(k, ts) : vistos.has(k)) return null;", para: "", testes: [PRO, REM], nome: "replay do pedido" },
  { id: "AR-17e", descricao: "pedido de sessão sem janela de tempo", arquivo: "src/nucleo/remoto/protocolo.ts", de: "if (Math.abs(agora - ts) > JANELA_TS_MS) return null;", para: "", testes: [PRO], nome: "replay do pedido" },
  { id: "AR-15", descricao: "permissão `mensagem_direta` sobe sem digitar PERMITIR", arquivo: "src/nucleo/remoto/dispositivos.ts", de: 'if (sobe && permissao === "mensagem_direta" && confirmacao !== CONFIRMACAO_DIRETA) return null;', para: "", testes: [ADV], nome: "ar15_permissao_so_pelo_desktop" },
  { id: "AR-16", descricao: "limite de taxa por IP deixa de valer", arquivo: "src/nucleo/remoto/servidor.ts", de: 'if (!(((req.url ?? "") === "/v1/canal" ? limiteIpCanal : limiteIp).tentar(ip))) {', para: "if (false) {", testes: [ADV, NET], nome: "ar16_flood|flood nas rotas" },
  { id: "AR-19a", descricao: "auditoria grava texto sem redigir", arquivo: "src/nucleo/jarvis/auditoria.ts", de: "truncarVisivel(redigirParaCanal(t, { max: n, ...(d.scrub === undefined ? {} : { scrub: d.scrub }) }), n)", para: "truncarVisivel(t, n)", testes: [ADV], nome: "ar19_sem_segredo_em_auditoria" },
  { id: "AR-20", descricao: "resumo de painel deixa de redigir segredo", arquivo: "src/nucleo/jarvis/snapshot.ts", de: "return truncarVisivel(redigirParaCanal(base, { max, ...(scrub === undefined ? {} : { scrub }) }), max);", para: "return truncarVisivel(base, max);", testes: [ADV], nome: "ar20_resumo_redige_segredo" },
  { id: "AR-21", descricao: "idempotência de client_request_id desligada", arquivo: "src/nucleo/jarvis/servico.ts", de: 'if (rid !== null && risco !== "leitura") {', para: "if (false) {", testes: [ADV], nome: "ar21_idempotencia" },
  { id: "AR-24", descricao: "pânico não revoga os dispositivos", arquivo: "src/nucleo/remoto/servico.ts", de: "const revogados = d.dispositivos.revogarTodos();", para: "const revogados = 0;", testes: [ADV], nome: "ar24_panico_fecha_tudo" },
  { id: "AR-25", descricao: "escrita remota continua com a tela bloqueada", arquivo: "src/nucleo/jarvis/servico.ts", de: 'if (e.ator === "remoto" && risco !== "leitura" && d.telaBloqueada?.() === true', para: 'if (false && e.ator === "remoto" && risco !== "leitura" && d.telaBloqueada?.() === true', testes: [ADV], nome: "ar25_tela_bloqueada" },
  { id: "AR-03a", descricao: "saída da LLM deixa de ser validada contra a lista fechada", arquivo: "src/nucleo/jarvis/classificador.ts", de: "const v = validarAcaoTipada(bruto);", para: "const v = { ok: true as const, acao: bruto as never };", testes: [ADV], nome: "ar03_llm_so_classifica" },
  { id: "AR-03b", descricao: "LLM passa a reescrever o texto enviado", arquivo: "src/nucleo/jarvis/classificador.ts", de: 'return { tipo: "acao", fonte: "llm", acao: { ...a, texto: textoSeguro(texto) } };', para: 'return { tipo: "acao", fonte: "llm", acao: a };', testes: [ADV], nome: "ar03_llm_so_classifica" },
  { id: "AR-22", descricao: "servidor deixa de assinar a sessão com a identidade fixada (o celular aceitaria impostor)", arquivo: "src/nucleo/remoto/protocolo.ts", de: "const sigS = deps.identidade.assinar(tr);", para: "const sigS = Buffer.alloc(64);", testes: [ADV, PRO], nome: "ar11_replay_quadros|ar22_identidade_fixada|negocia, o dispositivo" },
  { id: "AR-18", descricao: "ligar não exige o consentimento versionado", arquivo: "src/nucleo/remoto/servico.ts", de: "if (p.consentimento_versao !== TEXTO_CONSENTIMENTO_REMOTO_VERSAO) return { erro: \"consentimento_ausente\" };", para: "", testes: [ADV], nome: "ar18_nao_religa_sozinho" },
];
