// Lista de mutações da Fase 22 (relay cego, PWA, pareamento, revogação e pânico): cada item remove UMA mitigação de segurança (troca um trecho EXATO do fonte) e aponta o(s) teste(s) que PRECISAM
// falhar (T-22.26). Rodar: `node tests/scripts/mutacao-relay.mjs [AX-05a ...]`. A consistência (trecho aparece 1 vez, teste existe, nome do `-t` existe) é conferida por `mutacao-relay.test.ts`.
const ROT = "src/nucleo/relay/roteador.test.ts";
const SRV = "src/nucleo/relay/servidor.test.ts";
const CLI = "src/nucleo/remoto-estendido/cliente-relay.test.ts";
const REV = "src/nucleo/remoto-estendido/revogacao.test.ts";
const SVC = "src/nucleo/remoto-estendido/servico.test.ts";
const PAR = "src/nucleo/remoto-estendido/pareamento-relay.test.ts";
const WSC = "src/nucleo/remoto-estendido/ws-cliente.test.ts";
const CAN = "src/nucleo/remoto-estendido/canal.test.ts";
const PAD = "src/nucleo/remoto-estendido/padding.test.ts";
const MAN = "tests/pwa/manifesto.test.ts";
const UI = "tests/pwa/ui.test.ts";
const CRI = "tests/pwa/cripto.test.ts";
const FRO = "tests/scripts/relay-fronteira.test.ts";
const LIM = "src/nucleo/relay/limites.test.ts";
const CFG = "src/compartilhado/relay.test.ts";
const INT = "src/nucleo/remoto-estendido/integracao-relay.test.ts";

export const MUTACOES = [
  // ------------------------------------------------------------------------------------------------ relay (roteador/servidor)
  { id: "AX-05a", descricao: "slot do host: outro dono registra o mesmo canal (squatting)", arquivo: "src/nucleo/relay/roteador.ts", de: "if (!existente.hostPub.equals(pub)) return recusar(con.id, con);", para: "if (false) return recusar(con.id, con);", testes: [ROT], nome: "ax05_squatting_de_canal" },
  { id: "AX-05b", descricao: "prova de posse deixa de ser verificada", arquivo: "src/nucleo/relay/roteador.ts", de: "if (!verificarProva(pub, params, sig)) return recusar(con.id, con);", para: "if (false) return recusar(con.id, con);", testes: [ROT], nome: "ax05_squatting_de_canal|ax06_enumeracao_uniforme" },
  { id: "AX-05c", descricao: "slot do cliente aceita chave que o host não declarou", arquivo: "src/nucleo/relay/roteador.ts", de: "if (existente.cliPub !== null && !existente.cliPub.equals(pub)) return recusar(con.id, con);", para: "if (false) return recusar(con.id, con);", testes: [ROT, INT], nome: "ax05_squatting_de_canal|ax31_origem_nao_autentica|ax25_isolamento_de_canais" },
  { id: "AX-06", descricao: "recusa deixa de ter atraso uniforme", arquivo: "src/nucleo/relay/roteador.ts", de: '{ k: "fechar", con, codigo: 1008, atrasoMs: ATRASO_RECUSA_MS },', para: '{ k: "fechar", con, codigo: 1008 },', testes: [ROT], nome: "ax06_enumeracao_uniforme" },
  { id: "AX-18a", descricao: "quadro acima de 64 KiB deixa de fechar a conexão", arquivo: "src/nucleo/relay/roteador.ts", de: 'if (dados.byteLength > LIMITES_RELAY.quadro_max) return [{ k: "fechar", con, codigo: 1009 }];', para: "", testes: [ROT, SRV], nome: "ax18_flood_relay" },
  { id: "AX-18b", descricao: "quadro binário antes da prova de posse é aceito", arquivo: "src/nucleo/relay/roteador.ts", de: 'if (c.estado !== "ativo" || c.canal === undefined) return [{ k: "fechar", con, codigo: 1008 }];', para: 'if (c.canal === undefined) return [{ k: "fechar", con, codigo: 1008 }];', testes: [ROT, SRV], nome: "ax18_flood_relay|ax05_squatting_de_canal" },
  { id: "AX-22b", descricao: "nome local com ponto final passa pela validação da URL do relay", arquivo: "src/compartilhado/relay.ts", de: 'const h = u.hostname.replace(/\\.+$/, "");', para: "const h = u.hostname;", testes: [CFG], nome: "A-07" },
  { id: "AX-19d", descricao: "o host deixa de completar a URL sem caminho com o caminho de canal", arquivo: "src/nucleo/remoto-estendido/cliente-relay.ts", de: "url: urlDoCanalRelay(d.url),", para: "url: d.url,", testes: [CLI], nome: "A-06" },
  { id: "AX-18c", descricao: "limite por IP volta a usar o endereço IPv6 completo (um /64 inteiro escapa da cota)", arquivo: "src/nucleo/relay/limites.ts", de: 'return `${grupos.slice(0, 4).map((g) => parseInt(g, 16).toString(16)).join(":")}::/64`;', para: "return semZona;", testes: [LIM], nome: "chave de limite por origem" },
  { id: "AX-18d", descricao: "o servidor deixa de aplicar a chave /64 ao IP de origem", arquivo: "src/nucleo/relay/servidor.ts", de: 'return chaveDeIp(req.socket.remoteAddress ?? "desconhecido");', para: 'return req.socket.remoteAddress ?? "desconhecido";', testes: [FRO], nome: "ax18_chave_de_ip_no_servidor" },
  { id: "AX-27", descricao: "canal efêmero não morre no primeiro uso", arquivo: "src/nucleo/relay/roteador.ts", de: "return canal.efemero && canal.usado ? removerCanal(c.canal, con) : [];", para: "return [];", testes: [ROT], nome: "canal efêmero" },
  { id: "AX-27b", descricao: "canal efêmero não expira em 120 s", arquivo: "src/nucleo/relay/roteador.ts", de: "if (x !== undefined && x.efemero && agora - x.criado > LIMITES_RELAY.ttl_pareamento_ms) acoes.push(...removerCanal(k));", para: "", testes: [ROT], nome: "canal efêmero" },
  { id: "AX-32", descricao: "/healthz responde a qualquer origem", arquivo: "src/nucleo/relay/servidor.ts", de: 'INTERNO.test(p.remoto ?? "") && ', para: "", testes: [SRV], nome: "ax32_relay_nao_e_proxy" },
  // (AX-32b, CONNECT sem ouvinte, é mutante EQUIVALENTE: o Node já fecha o socket de um CONNECT sem ouvinte; o `http.on("connect")` explícito é só clareza, e o teste de CONNECT segue valendo)
  { id: "AX-23", descricao: "log passa a gravar o IP cru", arquivo: "src/nucleo/relay/log.ts", de: "...(ip === undefined ? {} : { ip: anonimo(ip) })", para: "...(ip === undefined ? {} : { ip })", testes: [SRV], nome: "ax23_log_sem_conteudo_nem_ip_cru" },
  { id: "AX-23b", descricao: "sal do IP deixa de girar por dia", arquivo: "src/nucleo/relay/log.ts", de: "if (d !== dia) {", para: "if (dia === -1) {", testes: [SRV], nome: "ax23_log_sem_conteudo_nem_ip_cru" },
  { id: "AX-33", descricao: "o relay passa a importar uma biblioteca de terceiros", arquivo: "src/nucleo/relay/main.ts", de: 'import { iniciarRelay, type OpcoesRelay } from "./servidor";', para: 'import { iniciarRelay, type OpcoesRelay } from "./servidor";\nimport "ws";', testes: [FRO], nome: "ax33_dependencias_do_relay_minimas" },
  // ------------------------------------------------------------------------------------------------ host (cliente do relay, invólucro, canal rotativo, padding)
  { id: "AX-02a", descricao: "o primeiro quadro adulterado deixa de fechar a conexão", arquivo: "src/nucleo/remoto-estendido/cliente-relay.ts", de: 'return derrubar("quadro_invalido"); // o primeiro quadro adulterado fecha (AX-02)', para: "return;", testes: [CLI], nome: "ax02_relay_nao_forja_quadro" },
  { id: "AX-02b", descricao: "quadro que não abre deixa de ser inválido", arquivo: "src/nucleo/remoto-estendido/transporte-relay.ts", de: 'if (x === null) return { k: "invalido" };', para: 'if (x === null) return { k: "ignorado", motivo: "enchimento" };', testes: [CLI], nome: "ax02_relay_nao_forja_quadro" },
  { id: "AX-03", descricao: "quadro duplicado pelo relay é executado de novo", arquivo: "src/nucleo/remoto-estendido/transporte-relay.ts", de: 'if (!lembrar(x.nonce)) return { k: "ignorado", motivo: "duplicado" };', para: "", testes: [CLI], nome: "ax03_relay_replay_reordem" },
  { id: "AX-19a", descricao: "backoff zera ao aceitar a conexão (relay que aceita e derruba vira tempestade)", arquivo: "src/nucleo/remoto-estendido/cliente-relay.ts", de: 'avisouIndisponivel = false;\n      mudar("registrado");', para: 'avisouIndisponivel = false;\n      tentativas = 0;\n      mudar("registrado");', testes: [CLI], nome: "ax19_backoff_reconexao" },
  { id: "AX-19b", descricao: "teto de tentativas por minuto some", arquivo: "src/nucleo/remoto-estendido/cliente-relay.ts", de: "if (recentes.length >= LIMITES_RELAY.tentativas_por_min) return", para: "if (false) return", testes: [CLI], nome: "ax19_backoff_reconexao" },
  { id: "AX-19c", descricao: "pong espontâneo do relay zera o backoff", arquivo: "src/nucleo/remoto-estendido/cliente-relay.ts", de: "if (!esperandoPong) return;", para: "", testes: [CLI], nome: "ax19_backoff_reconexao" },
  { id: "AX-07", descricao: "canal_id deixa de depender da época (identificador estável)", arquivo: "src/nucleo/remoto-estendido/canal.ts", de: 'return Buffer.concat([Buffer.from("xv/relay/canal/id"), e]);', para: 'return Buffer.from("xv/relay/canal/id");', testes: [CAN], nome: "ax07_canal_rotativo" },
  { id: "AX-08", descricao: "padding deixa de preencher até o bloco", arquivo: "src/nucleo/remoto-estendido/padding.ts", de: "const total = conteudo === null ? tamanhoEnchimento : tamanhoDoBloco(CABECALHO + c.length);", para: "const total = conteudo === null ? tamanhoEnchimento : CABECALHO + c.length;", testes: [PAD, INT], nome: "ax08_padding_de_quadros|ax01_relay_nunca_ve_texto_claro" },
  { id: "AX-22", descricao: "ws:// fora do teste passa a ser aceito", arquivo: "src/nucleo/remoto-estendido/ws-cliente.ts", de: 'if (ambiente !== "test" || !LOOPBACK_TESTE.test(o.url)) throw new ErroWs("url_insegura");', para: "", testes: [WSC], nome: "ax22_so_wss_fora_do_teste" },
  // ------------------------------------------------------------------------------------------------ serviço, pareamento, revogação e pânico
  { id: "AX-17a", descricao: "ligar sem consentimento versionado", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: "if (cfg.consentimento_versao !== TEXTO_CONSENTIMENTO_RELAY_VERSAO) return", para: "if (false) return", testes: [SVC], nome: "ax17_relay_nao_liga_sozinho" },
  { id: "AX-17b", descricao: "ligar sem o reconhecimento «experimental»", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: "if (!cfg.reconhecimento_experimental) return", para: "if (false) return", testes: [SVC], nome: "ax17_relay_nao_liga_sozinho" },
  { id: "AX-17c", descricao: "ligar com URL inválida", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: 'if (!urlAceita(cfg.url)) return { ok: false, motivo: "url_invalida" as const };', para: "", testes: [SVC], nome: "ax17_relay_nao_liga_sozinho" },
  { id: "AX-17d", descricao: "o reconhecimento deixa de valer por UMA ligação", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: "d.gravarConfig({ reconhecimento_experimental: false, habilitado: false, experimental: true });", para: "d.gravarConfig({ habilitado: false, experimental: true });", testes: [SVC], nome: "ligar consome o reconhecimento" },
  { id: "AX-34", descricao: "`habilitado` passa a vir do arquivo de preferências (liga sozinho no reinício)", edicoes: [
    { arquivo: "src/nucleo/remoto-estendido/config.ts", de: '.filter(([k]) => k !== "experimental" && k !== "habilitado" && !(urlTeste !== null && k === "url"))', para: ".filter(([k]) => !(urlTeste !== null && k === \"url\"))" },
    { arquivo: "src/nucleo/remoto-estendido/config.ts", de: "...(urlTeste === null ? {} : { url: urlTeste }), habilitado: false, experimental: true };", para: "...(urlTeste === null ? {} : { url: urlTeste }) };" },
  ], testes: [SVC, CFG], nome: "ax34_nao_habilita_por_padrao" },
  { id: "AX-28a", descricao: "o dispositivo recém-pareado nasce com permissão maior que `leitura`", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: "const r = d.remoto.parearIniciar(PERMISSAO_INICIAL_RELAY);", para: 'const r = d.remoto.parearIniciar("mensagem_confirmada");', testes: [SVC], nome: "ax28_dispositivo_nasce_leitura" },
  { id: "AX-28b", descricao: "qualquer dispositivo (ou fora da janela) pede o segredo de canal", arquivo: "src/nucleo/remoto-estendido/pareamento-relay.ts", de: "if (em === undefined || d.relogio.agora() - em > JANELA_ENTREGA_SEGREDO_MS) {", para: "if (false) {", testes: [SVC, PAR], nome: "ax28_so_o_dispositivo_pareado|só o dispositivo pareado AGORA|ignora o que não é seu" },
  { id: "AX-28c", descricao: "o segredo de canal pode ser entregue mais de uma vez", arquivo: "src/nucleo/remoto-estendido/pareamento-relay.ts", de: 'if (existente !== null) return { t: "erro", e: "ja_emitido" };', para: "", testes: [SVC, PAR], nome: "ax28_dispositivo_nasce_leitura|ignora o que não é seu" },
  { id: "AX-28d", descricao: "canal_segredo concorrente entrega dois segredos (a permissão só é consumida depois do await)", arquivo: "src/nucleo/remoto-estendido/pareamento-relay.ts", de: "d.recentes.delete(disp.id); // consome a permissão AGORA, antes de qualquer `await`: um segundo pedido concorrente cai em `nao_permitido` (A-03: nunca dois segredos)", para: "", testes: [PAR], nome: "dois `canal_segredo` CONCORRENTES" },
  { id: "AX-16e", descricao: "cliente do canal definitivo sobe mesmo depois de pânico/desligar durante a leitura do cofre", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: 'if (!ligado || clientes.has(id) || d.remoto.chaveDoDispositivo(id) === null || pub === null || bruto === null || bruto === "") return false;', para: 'if (clientes.has(id) || pub === null || bruto === null || bruto === "") return false;', testes: [SVC], nome: "desligar` no meio da subida do canal definitivo" },
  { id: "AX-15c", descricao: "revogar com o relay desligado deixa o segredo de canal no cofre", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: "if (ligado || clientes.has(id) || d.repo.obter(id) !== null) revogacao.aoRevogado(id);", para: "if (ligado || clientes.has(id)) revogacao.aoRevogado(id);", testes: [SVC], nome: "revogar com o relay DESLIGADO" },
  { id: "AX-27c", descricao: "«Recusar» no desktop deixa o efêmero e o pedido abertos", arquivo: "src/nucleo/remoto-estendido/servico.ts", de: 'encerrarPareamento("negado");', para: "", testes: [SVC], nome: "ax27_pareamento_via_relay_uso_unico" },
  { id: "AX-15a", descricao: "revogar deixa o canal do relay aberto (sem desregistrar)", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "if (c !== undefined) fecharTudo(c);", para: "", testes: [SVC, REV], nome: "revogar um não afeta os outros|revogar UM dispositivo" },
  { id: "AX-15b", descricao: "revogar deixa o segredo de canal no cofre", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "void d.apagarSegredo(nomeSegredoCanal(id)).catch(() => undefined);", para: "", testes: [SVC, REV], nome: "revogar um não afeta os outros|revogar UM dispositivo" },
  { id: "AX-16a", descricao: "pânico não fecha os sockets", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "for (const c of d.clientes.values()) fecharTudo(c);", para: "", testes: [SVC, REV], nome: "ax16_panico_zero_sockets" },
  { id: "AX-16b", descricao: "pânico não revoga todos os dispositivos no host", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "await d.revogarTodosNoHost().catch(() => undefined);", para: "", testes: [SVC, REV], nome: "ax16_panico_zero_sockets" },
  { id: "AX-16c", descricao: "pânico deixa os segredos de canal no cofre", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "await Promise.all(ids.map((id) => d.apagarSegredo(nomeSegredoCanal(id)).catch(() => undefined)));", para: "", testes: [SVC, REV], nome: "ax16_panico_zero_sockets" },
  { id: "AX-16d", descricao: "pânico não cancela o pareamento em curso", arquivo: "src/nucleo/remoto-estendido/revogacao.ts", de: "if (e !== null) fecharTudo(e);\n      d.cancelarPareamento();", para: "", testes: [SVC, REV], nome: "ax16_panico_zero_sockets" },
  // ------------------------------------------------------------------------------------------------ PWA (cripto, manifesto, saída em texto)
  { id: "AX-09", descricao: "arquivo do shell deixa de ser conferido por hash", arquivo: "pwa/verificar.js", de: "if (bytes === null || !(await arquivoConfere(bytes, entrada))) return", para: "if (bytes === null) return", testes: [MAN], nome: "ax09_shell_adulterado_nao_executa" },
  { id: "AX-09b", descricao: "assinatura do manifesto deixa de ser exigida", arquivo: "pwa/verificar.js", de: "if (!(await assinaturaValida(manifestoBytes, assinaturaB64, chaves))) return", para: "if (false) return", testes: [MAN], nome: "ax09_shell_adulterado_nao_executa|ax10_atualizacao_so_assinada" },
  { id: "AX-09c", descricao: "assinatura do manifesto aceita base64 não canônico (duas grafias da mesma assinatura)", arquivo: "pwa/verificar.js", de: "if (sig.length !== 64 || bytesParaB64(sig) !== assinaturaB64) return false;", para: "if (sig.length !== 64) return false;", testes: ["tests/fuzz/regressoes.test.ts"], nome: "R-FUZZ-02" },
  { id: "AX-14b", descricao: "401 no início da sessão volta a apagar o pareamento do celular (relay hostil ou relógio errado)", arquivo: "pwa/protocolo-cliente.js", de: '          recusas401++;\n          if (recusas401 >= 3) emitir({ erro: "sessao_recusada" });', para: "          return revogado();", testes: ["tests/pwa/pareamento-relay.integracao.test.ts"], nome: "A-01: 401 no início da sessão" },
  { id: "AX-10b", descricao: "SW sem piso de versão: manifesto assinado antigo volta depois de limpar o armazenamento", arquivo: "pwa/sw-fonte.js", de: 'versaoInstalada: Math.max(await lerMeta("versao"), VERSAO_SW - 1)', para: 'versaoInstalada: await lerMeta("versao")', testes: [MAN], nome: "A-12" },
  { id: "AX-09d", descricao: "o SW deixa de repor os cabeçalhos de segurança nas respostas do cache", arquivo: "pwa/sw-fonte.js", de: '"Cache-Control": "no-store", ...CABECALHOS_SEG', para: '"Cache-Control": "no-store"', testes: ["tests/pwa-navegador.e2e.test.ts"], config: "vitest.e2e.config.mts", nome: "é instalável e verificado" },
  { id: "AX-10", descricao: "atualização com versão menor (rollback) é aceita", arquivo: "pwa/verificar.js", de: 'if (!(m.versao > versaoInstalada)) return { ok: false, motivo: "versao" };', para: "", testes: [MAN], nome: "ax10_atualizacao_so_assinada" },
  { id: "AX-12", descricao: "texto vindo do desktop passa a ser HTML", arquivo: "pwa/ui.js", de: "if (texto !== undefined && texto !== null) e.textContent = String(texto);", para: "if (texto !== undefined && texto !== null) e.innerHTML = String(texto);", testes: [UI], nome: "ax12_saida_so_texto" },
  { id: "AX-13", descricao: "chave do dispositivo passa a ser extraível", arquivo: "pwa/cripto.js", de: 'generateKey({ name: "ECDSA", namedCurve: "P-256" }, false, ["sign", "verify"])', para: 'generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"])', testes: [CRI], nome: "ax13_chave_nao_extraivel" },
];
